#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
GROMACS ITP File Builder

Generates GROMACS hybrid topology files with typeB/chargeB/massB encoding for
FEP calculations and can reconstruct full bonded sections from two source
ligand ITP files.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import json
import re
from typing import Dict, List, Optional, Tuple

from ..core.hybrid_topology import HybridAtom


@dataclass
class HybridAtomRecord:
    """Parsed atom row from a hybrid ITP."""

    index: int
    name: str
    state_a_type: str
    state_a_charge: float
    mass: float
    state_b_type: Optional[str] = None
    state_b_charge: Optional[float] = None
    mass_b: Optional[float] = None
    name_b: Optional[str] = None  # B-side atom name for correct bonded mapping
    source_a_index: Optional[int] = None  # Source ligand A atom index (for direct bond mapping)
    source_b_index: Optional[int] = None  # Source ligand B atom index (for direct bond mapping)


@dataclass
class InteractionTerm:
    """Topology interaction term from a source ligand ITP."""

    atoms: Tuple[int, ...]
    funct: int
    params: List[str]


class ITPBuilder:
    """
    GROMACS ITP file generator for FEP calculations.

    Parameters
    ----------
    hybrid_atoms : List[HybridAtom]
        List of hybrid atoms with A/B state parameters.
    hybrid_params : Dict[str, List]
        Hybrid parameter dictionary. Recognized keys:
        - ``bonds``
        - ``pairs``
        - ``angles``
        - ``dihedrals``
        - ``impropers``
    """

    _SECTION_ATOM_COUNT = {
        "bonds": 2,
        "pairs": 2,
        "angles": 3,
        "dihedrals": 4,
        "impropers": 4,
    }

    def __init__(self, hybrid_atoms: List[HybridAtom], hybrid_params: Dict[str, List]):
        self.hybrid_atoms = hybrid_atoms
        self.hybrid_params = hybrid_params

    def write_itp(self, output_path: str, molecule_name: str = "HYB") -> None:
        """Write a hybrid topology ITP file."""
        with open(output_path, "w") as f:
            f.write("; GROMACS topology file for FEP calculation\n")
            f.write("; Generated by PRISM-FEP\n")
            f.write(";\n\n")

            # Write atomtypes section for dummy atoms
            atomtypes_section = self._get_atomtypes_section()
            if atomtypes_section:
                f.write(atomtypes_section)

            f.write("[ moleculetype ]\n")
            f.write("; Name            nrexcl\n")
            f.write(f"{molecule_name:16s}     3\n\n")

            atoms_section = self._get_atoms_section()
            f.write(atoms_section)

            # Validate that at least one atom has B-state parameters
            self._validate_perturbed_atoms_exist(atoms_section)

            if self.hybrid_params.get("bonds"):
                f.write(self._get_interaction_section("bonds", ";  ai    aj funct"))
            if self.hybrid_params.get("pairs"):
                f.write(self._get_interaction_section("pairs", ";  ai    aj funct"))
            if self.hybrid_params.get("angles"):
                f.write(self._get_interaction_section("angles", ";  ai    aj    ak funct"))
            if self.hybrid_params.get("dihedrals"):
                f.write(self._get_interaction_section("dihedrals", ";  ai    aj    ak    al funct"))
            if self.hybrid_params.get("impropers"):
                f.write(self._get_interaction_section("impropers", ";  ai    aj    ak    al funct"))

    def _get_atomtypes_section(self) -> str:
        """
        Generate the ``[ atomtypes ]`` section for dummy atoms.

        Note: This section is now skipped because atomtypes are included via
        atomtypes_hybrid.itp in the main topology file to avoid duplicate
        definitions and ordering issues.
        """
        # Return empty string - atomtypes are now handled by atomtypes_hybrid.itp
        return ""

    def _get_atoms_section(self) -> str:
        """Generate the ``[ atoms ]`` section."""
        lines = [
            "[ atoms ]",
            ";   nr       type  resnr residue  atom   cgnr     charge       mass  ",
            ";                                                                      typeB    chargeB      massB",
        ]

        for atom in self.hybrid_atoms:
            # CRITICAL: Add source index comments for bonded term reconstruction
            # This ensures build_hybrid_params_from_itps can reconstruct bonded terms
            # by mapping source ligand atoms to hybrid topology atoms
            source_a_idx = getattr(atom, "source_a_index", None)
            source_b_idx = getattr(atom, "source_b_index", None)
            if source_a_idx is not None:
                lines.append(f"; source_a_index: {source_a_idx}")
            if source_b_idx is not None:
                lines.append(f"; source_b_index: {source_b_idx}")

            # Add comment for B-side atom name BEFORE the atom line
            # This ensures _parse_hybrid_atom_records() can read the comment and
            # associate it with the correct atom
            if atom.name_b:
                lines.append(f"; name_b (state B): {atom.name_b}")

            line = f"{atom.index:6d} {atom.state_a_type:>10s}      1     LIG {atom.name:>5s}      1 "
            line += f"{atom.state_a_charge:10.6f} {atom.mass:10.5f}"

            # Write B-state columns if:
            # 1. Atom is marked as perturbed (transformed/surrounding), OR
            # 2. Type differs, OR
            # 3. Charge differs, OR
            # 4. Mass differs
            if atom.state_b_type is not None and atom.state_b_charge is not None:
                should_write_b = (
                    getattr(atom, "is_perturbed", False)  # Perturbed atoms always write B
                    or atom.state_b_type != atom.state_a_type
                    or abs(atom.state_b_charge - atom.state_a_charge) > 1e-6
                    or (atom.mass_b is not None and abs(atom.mass_b - atom.mass) > 1e-6)
                )

                if should_write_b:
                    line += f" {atom.state_b_type:>10s} {atom.state_b_charge:10.6f}"
                    mass_b = atom.mass_b if atom.mass_b is not None else atom.mass
                    line += f" {mass_b:10.5f}"

            lines.append(line)

        lines.append("")
        return "\n".join(lines) + "\n"

    def _validate_perturbed_atoms_exist(self, atoms_section: str) -> None:
        """
        Validate that at least one atom has B-state parameters.

        This ensures the hybrid topology actually represents a transformation.
        If no atoms have typeB/chargeB/massB, the FEP calculation is meaningless.

        Parameters
        ----------
        atoms_section : str
            The generated [ atoms ] section text

        Raises
        ------
        ValueError
            If no atoms have B-state parameters
        """
        # Count lines with B-state columns (more than 8 fields)
        b_state_count = 0
        for line in atoms_section.split("\n"):
            if line.strip() and not line.strip().startswith(";"):
                fields = line.split()
                if len(fields) > 8:  # Has typeB, chargeB, massB
                    b_state_count += 1

        if b_state_count == 0:
            total_atoms = len(self.hybrid_atoms)
            perturbed_count = sum(1 for a in self.hybrid_atoms if getattr(a, "is_perturbed", False))

            error_msg = (
                f"FEP validation error: No atoms have B-state parameters!\n"
                f"  Total atoms: {total_atoms}\n"
                f"  Atoms marked as perturbed: {perturbed_count}\n"
                f"  Atoms with B-state columns written: 0\n\n"
                f"This indicates a problem with the atom mapping or charge equalization.\n"
                f"Possible causes:\n"
                f"  1. All atoms classified as 'common' with identical A/B parameters\n"
                f"  2. Charge redistribution eliminated all differences\n"
                f"  3. Mapping configuration too strict (try increasing charge_cutoff)\n\n"
                f"Suggestions:\n"
                f"  - Check mapping results in mapping.html\n"
                f"  - Verify ligands A and B are actually different\n"
                f"  - Try charge_strategy='none' to preserve original charges\n"
                f"  - Increase charge_cutoff (e.g., from 0.05 to 0.1)\n"
            )
            raise ValueError(error_msg)

    def _get_interaction_section(self, section: str, header: str) -> str:
        """Generate a bonded interaction section."""
        section_name = "[ dihedrals ]" if section == "impropers" else f"[ {section} ]"
        lines = [section_name, header]

        for term in self.hybrid_params.get(section, []):
            atom_text = " ".join(f"{idx:6d}" for idx in term["atoms"])
            line = f"{atom_text} {term['funct']:6d}"
            params_a = term.get("params_a", [])
            params_b = term.get("params_b", [])
            if params_a:
                line += " " + " ".join(params_a)
            if params_b:
                line += " " + " ".join(params_b)
            lines.append(line)

        lines.append("")
        return "\n".join(lines) + "\n"

    @classmethod
    def build_hybrid_params_from_itps(
        cls,
        hybrid_itp: str,
        ligand_a_itp: str,
        ligand_b_itp: str,
        ligand_a_structure: Optional[str] = None,
        ligand_b_structure: Optional[str] = None,
        atom_types_a: Optional[Dict[int, str]] = None,
        atom_types_b: Optional[Dict[int, str]] = None,
    ) -> Dict[str, List]:
        """
        Reconstruct complete hybrid bonded terms from a hybrid atoms-only ITP and
        two source ligand ITP files.
        """
        hybrid_records = cls._parse_hybrid_atom_records(Path(hybrid_itp).read_text())
        cls._recover_source_indices_from_mapping_html(
            hybrid_records,
            Path(hybrid_itp).with_name("mapping.html"),
        )
        source_a = cls._parse_source_itp(Path(ligand_a_itp).read_text(), structure_file=ligand_a_structure)
        source_b = cls._parse_source_itp(Path(ligand_b_itp).read_text(), structure_file=ligand_b_structure)

        cls._recover_missing_source_indices(
            hybrid_records,
            source_a.get("atom_types", {}),
            source_b.get("atom_types", {}),
            source_a.get("atom_names", {}),
            source_b.get("atom_names", {}),
        )

        # Try to use index-based mapping first, fallback to name-based if needed
        try:
            index_map_a, index_map_b = cls._build_state_index_maps(hybrid_records)
            use_index_mapping = True
        except Exception:
            name_map_a, name_map_b = cls._build_state_name_maps_fallback(hybrid_records)
            use_index_mapping = False

        # Build sets of hybrid indices that are dummy in each state
        dummy_in_a: set = {r.index for r in hybrid_records if r.state_a_type.startswith("DUM_")}
        dummy_in_b: set = {r.index for r in hybrid_records if (r.state_b_type or "").startswith("DUM_")}

        # Remap atom types from source IDs to hybrid IDs
        hybrid_atom_types_a = None
        hybrid_atom_types_b = None
        if use_index_mapping:
            if atom_types_a:
                hybrid_atom_types_a = cls._remap_atom_types_to_hybrid_by_index(atom_types_a, index_map_a)
            if atom_types_b:
                hybrid_atom_types_b = cls._remap_atom_types_to_hybrid_by_index(atom_types_b, index_map_b)
        else:
            if atom_types_a:
                hybrid_atom_types_a = cls._remap_atom_types_to_hybrid(atom_types_a, source_a["atom_names"], name_map_a)
            if atom_types_b:
                hybrid_atom_types_b = cls._remap_atom_types_to_hybrid(atom_types_b, source_b["atom_names"], name_map_b)

        hybrid_params: Dict[str, List] = {key: [] for key in cls._SECTION_ATOM_COUNT}
        for section in cls._SECTION_ATOM_COUNT:
            if use_index_mapping:
                hybrid_params[section] = cls._merge_section_terms(
                    section=section,
                    terms_a=source_a["sections"].get(section, []),
                    terms_b=source_b["sections"].get(section, []),
                    atom_names_a=source_a["atom_names"],
                    atom_names_b=source_b["atom_names"],
                    atom_types_a=source_a.get("atom_types", {}),
                    atom_types_b=source_b.get("atom_types", {}),
                    index_map_a=index_map_a,
                    index_map_b=index_map_b,
                    dummy_in_a=dummy_in_a,
                    dummy_in_b=dummy_in_b,
                    atom_types_a_hybrid=hybrid_atom_types_a,
                    atom_types_b_hybrid=hybrid_atom_types_b,
                )
            else:
                hybrid_params[section] = cls._merge_section_terms(
                    section=section,
                    terms_a=source_a["sections"].get(section, []),
                    terms_b=source_b["sections"].get(section, []),
                    atom_names_a=source_a["atom_names"],
                    atom_names_b=source_b["atom_names"],
                    atom_types_a=source_a.get("atom_types", {}),
                    atom_types_b=source_b.get("atom_types", {}),
                    name_map_a=name_map_a,
                    name_map_b=name_map_b,
                    dummy_in_a=dummy_in_a,
                    dummy_in_b=dummy_in_b,
                    atom_types_a_hybrid=hybrid_atom_types_a,
                    atom_types_b_hybrid=hybrid_atom_types_b,
                )
        return hybrid_params

    @classmethod
    def _recover_missing_source_indices(
        cls,
        hybrid_records: List[HybridAtomRecord],
        source_atom_types_a: Dict[int, str],
        source_atom_types_b: Dict[int, str],
        source_atom_names_a: Dict[int, str],
        source_atom_names_b: Dict[int, str],
    ) -> None:
        """Recover source atom indices for legacy hybrid ITPs missing index comments.

        Older scaffolds may contain only ``name_b`` comments in ``hybrid_atoms_temp.itp``.
        That forces a weak name-based bonded-term merge and produces large numbers of
        spurious zero-force terms for generators such as LigParGen, where source ITP
        atom names are generic but atom types are unique. Recover indices in-place
        before we choose the mapping strategy.
        """

        def unique_type_map(source_atom_types: Dict[int, str]) -> Dict[str, int]:
            buckets: Dict[str, List[int]] = {}
            for atom_index, atom_type in source_atom_types.items():
                buckets.setdefault(atom_type, []).append(atom_index)
            return {atom_type: indices[0] for atom_type, indices in buckets.items() if len(indices) == 1}

        unique_a = unique_type_map(source_atom_types_a)
        unique_b = unique_type_map(source_atom_types_b)
        name_to_index_a = {name: idx for idx, name in source_atom_names_a.items()}
        name_to_index_b = {name: idx for idx, name in source_atom_names_b.items()}

        def normalized_state_a_name(record: HybridAtomRecord) -> str:
            if record.name.endswith("A") and not record.state_a_type.startswith("DUM_"):
                return record.name[:-1]
            return record.name

        for record in hybrid_records:
            if record.source_a_index is None and not record.state_a_type.startswith("DUM_"):
                inferred_a = name_to_index_a.get(normalized_state_a_name(record))
                if inferred_a is None:
                    inferred_a = unique_a.get(record.state_a_type)
                record.source_a_index = inferred_a

            state_b_type = record.state_b_type or record.state_a_type or ""
            if record.source_b_index is None and state_b_type and not state_b_type.startswith("DUM_"):
                state_b_name = record.name_b or record.name
                if state_b_name.endswith("B"):
                    state_b_name = state_b_name[:-1]
                inferred_b = name_to_index_b.get(state_b_name)
                if inferred_b is None:
                    inferred_b = unique_b.get(state_b_type)
                record.source_b_index = inferred_b

    @classmethod
    def _recover_source_indices_from_mapping_html(
        cls, hybrid_records: List[HybridAtomRecord], mapping_html: Path
    ) -> None:
        """Recover source indices from mapping.html for legacy scaffolds.

        mapping.html stores the authoritative atom correspondence used to build
        the hybrid topology. Older hybrid_atoms_temp.itp files may have dropped
        source index comments entirely; in that case, reconstructing from the
        saved mapping is more reliable than guessing from atom names or types.
        """
        if not mapping_html.exists():
            return
        if all(r.source_a_index is not None or r.state_a_type.startswith("DUM_") for r in hybrid_records) and all(
            r.source_b_index is not None
            or (r.state_b_type or "").startswith("DUM_")
            or (r.state_b_type is None and not getattr(r, "name_b", None))
            for r in hybrid_records
        ):
            return

        text = mapping_html.read_text()

        def extract_js_json(name: str):
            match = re.search(rf"const\\s+{name}\\s*=\\s*(.*?);", text, re.S)
            if not match:
                return None
            return json.loads(match.group(1))

        atoms_a = extract_js_json("ATOMS_A")
        atoms_b = extract_js_json("ATOMS_B")
        correspondence = extract_js_json("CORRESPONDENCE")
        if not atoms_a or not atoms_b or not correspondence:
            return

        b_match_by_a_source = {}
        matched_b_positions = set()
        for a_key, b_key in correspondence.items():
            if not a_key.startswith("a_") or not b_key.startswith("b_"):
                continue
            a_pos = int(a_key.split("_", 1)[1])
            b_pos = int(b_key.split("_", 1)[1])
            if a_pos < len(atoms_a) and b_pos < len(atoms_b):
                b_match_by_a_source[int(atoms_a[a_pos]["sourceIndex"])] = int(atoms_b[b_pos]["sourceIndex"])
                matched_b_positions.add(b_pos)

        transformed_b_sources = [
            int(atom["sourceIndex"])
            for idx, atom in enumerate(atoms_b)
            if atom.get("classification") == "transformed" and idx not in matched_b_positions
        ]
        transformed_b_iter = iter(transformed_b_sources)

        next_a_source = 1
        for record in hybrid_records:
            state_a_dummy = record.state_a_type.startswith("DUM_")
            state_b_type = record.state_b_type or ""
            state_b_dummy = state_b_type.startswith("DUM_")

            if not state_a_dummy:
                if record.source_a_index is None:
                    record.source_a_index = next_a_source
                if record.source_a_index is not None:
                    next_a_source = max(next_a_source, record.source_a_index + 1)

            if record.source_b_index is not None:
                continue

            if not state_a_dummy and not state_b_dummy:
                if record.source_a_index is not None:
                    record.source_b_index = b_match_by_a_source.get(record.source_a_index)
                continue

            if state_a_dummy and state_b_type and not state_b_dummy:
                record.source_b_index = next(transformed_b_iter, None)

    @classmethod
    def write_complete_hybrid_itp(
        cls,
        output_path: str,
        hybrid_itp: str,
        ligand_a_itp: str,
        ligand_b_itp: str,
        molecule_name: str = "HYB",
        ligand_a_structure: Optional[str] = None,
        ligand_b_structure: Optional[str] = None,
        atom_types_a: Optional[Dict[int, str]] = None,
        atom_types_b: Optional[Dict[int, str]] = None,
    ) -> Dict[str, List]:
        """
        Write a complete hybrid ITP using the atoms section from ``hybrid_itp``
        and bonded terms reconstructed from source ligand ITPs.
        """
        content = Path(hybrid_itp).read_text()
        hybrid_records = cls._parse_hybrid_atom_records(content)
        hybrid_atoms = [cls._record_to_hybrid_atom(record) for record in hybrid_records]
        hybrid_params = cls.build_hybrid_params_from_itps(
            hybrid_itp,
            ligand_a_itp,
            ligand_b_itp,
            ligand_a_structure=ligand_a_structure,
            ligand_b_structure=ligand_b_structure,
            atom_types_a=atom_types_a,
            atom_types_b=atom_types_b,
        )
        cls(hybrid_atoms, hybrid_params).write_itp(output_path, molecule_name=molecule_name)
        return hybrid_params

    @staticmethod
    def _record_to_hybrid_atom(record: HybridAtomRecord) -> HybridAtom:
        # Infer is_perturbed from the presence of B-state parameters
        # If record has B-state type/charge, it's perturbed
        is_perturbed = record.state_b_type is not None and record.state_b_charge is not None

        return HybridAtom(
            name=record.name,
            name_b=record.name_b,
            index=record.index,
            state_a_type=record.state_a_type,
            state_a_charge=record.state_a_charge,
            state_b_type=record.state_b_type,
            state_b_charge=record.state_b_charge,
            mass=record.mass,
            mass_b=record.mass_b,
            is_perturbed=is_perturbed,
            source_a_index=record.source_a_index,
            source_b_index=record.source_b_index,
        )

    @classmethod
    def _parse_hybrid_atom_records(cls, content: str) -> List[HybridAtomRecord]:
        """Parse hybrid atom rows from an ITP content string."""
        records: List[HybridAtomRecord] = []
        in_atoms = False
        name_b_for_next_atom = None  # Store name_b from comment for next atom
        source_a_index_for_next_atom = None  # Store source_a_index from comment
        source_b_index_for_next_atom = None  # Store source_b_index from comment

        for line in content.splitlines():
            stripped = line.strip()
            if stripped.lower() == "[ atoms ]":
                in_atoms = True
                continue
            if stripped.startswith("[") and in_atoms:
                break

            # Parse source indices from comments
            if in_atoms and stripped.startswith(";"):
                if "source_a_index:" in stripped:
                    try:
                        source_a_index_for_next_atom = int(stripped.split("source_a_index:")[-1].strip())
                    except ValueError:
                        pass
                    continue
                if "source_b_index:" in stripped:
                    try:
                        source_b_index_for_next_atom = int(stripped.split("source_b_index:")[-1].strip())
                    except ValueError:
                        pass
                    continue
                # Parse name_b from comment (format: "; name_b (state B): XXXX")
                if "name_b (state B):" in stripped:
                    name_b_for_next_atom = stripped.split("name_b (state B):")[-1].strip()
                    continue

            if not in_atoms or not stripped or stripped.startswith(";"):
                continue

            parts = stripped.split()
            if len(parts) < 8:
                continue

            state_b_type = None
            state_b_charge = None
            mass_b = None
            if len(parts) >= 10 and not cls._looks_like_float(parts[8]):
                state_b_type = parts[8]
                state_b_charge = float(parts[9])
                if len(parts) >= 11 and cls._looks_like_float(parts[10]):
                    mass_b = float(parts[10])
                else:
                    mass_b = float(parts[7])

            record = HybridAtomRecord(
                index=int(parts[0]),
                name=parts[4],
                state_a_type=parts[1],
                state_a_charge=float(parts[6]),
                mass=float(parts[7]),
                state_b_type=state_b_type,
                state_b_charge=state_b_charge,
                mass_b=mass_b,
                name_b=name_b_for_next_atom,  # Use name_b from comment if available
            )
            # Store source indices if available
            if source_a_index_for_next_atom is not None:
                record.source_a_index = source_a_index_for_next_atom
            if source_b_index_for_next_atom is not None:
                record.source_b_index = source_b_index_for_next_atom

            records.append(record)
            name_b_for_next_atom = None  # Reset for next atom
            source_a_index_for_next_atom = None  # Reset for next atom
            source_b_index_for_next_atom = None  # Reset for next atom

        return records

    @classmethod
    def _build_state_index_maps(cls, hybrid_records: List[HybridAtomRecord]) -> Tuple[Dict[int, int], Dict[int, int]]:
        """Build source atom index to hybrid index maps using source_a_index/source_b_index fields.

        CRITICAL FIX: Use direct index mapping instead of name-based mapping to prevent self-bonds.
        This requires HybridAtomRecord to have source_a_index and source_b_index fields set.

        For example:
        - Source ligand A atom 21 → Hybrid atom 48
        - Source ligand B atom 27 → Hybrid atom 48

        Returns:
            Tuple of (index_map_a, index_map_b) where:
            - index_map_a: {source_a_index: hybrid_index} for state A
            - index_map_b: {source_b_index: hybrid_index} for state B
        """
        map_a: Dict[int, int] = {}
        map_b: Dict[int, int] = {}

        for record in hybrid_records:
            # Use source_a_index and source_b_index if available
            if hasattr(record, "source_a_index") and record.source_a_index is not None:
                map_a[record.source_a_index] = record.index
            if hasattr(record, "source_b_index") and record.source_b_index is not None:
                map_b[record.source_b_index] = record.index

        # If source indices are incomplete, let the caller explicitly fall back to
        # name-based mapping instead of returning a different key type here.
        if not map_a or not map_b:
            raise ValueError("source_a_index/source_b_index not available")

        return map_a, map_b

    @classmethod
    def _build_state_name_maps_fallback(
        cls, hybrid_records: List[HybridAtomRecord]
    ) -> Tuple[Dict[Tuple[str, str], int], Dict[Tuple[str, str], int]]:
        """Fallback name-based mapping when source indices are not available."""
        map_a: Dict[Tuple[str, str], int] = {}
        map_b: Dict[Tuple[str, str], int] = {}

        for record in hybrid_records:
            state_a_dummy = record.state_a_type.startswith("DUM_")
            state_b_dummy = (record.state_b_type or "").startswith("DUM_")

            if record.name.endswith("A") and state_b_dummy and not state_a_dummy:
                map_a[(record.state_a_type, record.name[:-1])] = record.index
                continue

            if record.name.endswith("B") and state_a_dummy and not state_b_dummy:
                if record.state_b_type:
                    map_b[(record.state_b_type, record.name[:-1])] = record.index
                continue

            if not state_a_dummy:
                map_a[(record.state_a_type, record.name)] = record.index
            # Common atoms often do not write explicit B-state columns when the
            # B-state type/charge/mass are identical to state A. They still need
            # to participate in B-state bonded-term reconstruction, so mirror the
            # A-state type into the B-state name map when no explicit B type is
            # present and the atom is not a dummy in either state.
            if not state_b_dummy:
                b_name = record.name_b if record.name_b else record.name
                b_type = record.state_b_type if record.state_b_type else record.state_a_type
                map_b[(b_type, b_name)] = record.index

        return map_a, map_b

    @classmethod
    def _parse_source_itp(cls, content: str, structure_file: Optional[str] = None) -> Dict[str, Dict]:
        """Parse atoms and bonded sections from a source ligand ITP."""
        atom_names: Dict[int, str] = {}
        atom_types: Dict[int, str] = {}
        sections: Dict[str, List[InteractionTerm]] = {key: [] for key in cls._SECTION_ATOM_COUNT}

        current_section: Optional[str] = None
        for raw_line in content.splitlines():
            stripped = raw_line.strip()
            if not stripped:
                continue
            if stripped.startswith("#"):
                continue
            if stripped.startswith("["):
                lower = stripped.lower()
                if lower.startswith("[ atoms ]"):
                    current_section = "atoms"
                elif lower.startswith("[ bonds ]"):
                    current_section = "bonds"
                elif lower.startswith("[ pairs ]"):
                    current_section = "pairs"
                elif lower.startswith("[ angles ]"):
                    current_section = "angles"
                elif lower.startswith("[ dihedrals ]"):
                    current_section = "impropers" if "improper" in lower else "dihedrals"
                else:
                    current_section = None
                continue
            if stripped.startswith(";") or current_section is None:
                continue

            line = raw_line.split(";", 1)[0].strip()
            if not line:
                continue
            parts = line.split()

            if current_section == "atoms":
                if len(parts) >= 5:
                    try:
                        atom_index = int(parts[0])
                    except ValueError:
                        continue
                    atom_names[atom_index] = parts[4]
                    atom_types[atom_index] = parts[1]
                continue

            atom_count = cls._SECTION_ATOM_COUNT[current_section]
            if len(parts) < atom_count + 1:
                continue

            try:
                atom_indices = tuple(int(parts[i]) for i in range(atom_count))
                funct = int(parts[atom_count])
            except ValueError:
                continue
            params = parts[atom_count + 1 :]
            sections[current_section].append(InteractionTerm(atoms=atom_indices, funct=funct, params=params))

        atom_names = cls._remap_generic_atom_names(atom_names, sections.get("bonds", []), structure_file)
        return {"atom_names": atom_names, "atom_types": atom_types, "sections": sections}

    @classmethod
    def _remap_generic_atom_names(
        cls, atom_names: Dict[int, str], bond_terms: List[InteractionTerm], structure_file: Optional[str]
    ) -> Dict[int, str]:
        """
        Remap generic source-I T P atom names onto the original MOL2 atom names.

        OPLS/OpenFF source ITPs may use generator-local labels that do not match the
        aligned ligand coordinates used for atom mapping. When a MOL2 template is
        available, use graph isomorphism on the bond graph to recover the original
        atom naming so bonded terms can be merged against the hybrid topology.
        """
        if not structure_file:
            return atom_names
        structure_file_lower = structure_file.lower()
        if structure_file_lower.endswith(".pdb"):
            pdb_names = cls._read_pdb_atom_names(structure_file)
            if pdb_names and len(pdb_names) >= len(atom_names):
                remapped = {}
                for itp_idx, atom_name in atom_names.items():
                    remapped[itp_idx] = pdb_names.get(itp_idx, atom_name)
                return remapped
            return atom_names
        if not structure_file_lower.endswith(".mol2"):
            return atom_names
        if not atom_names or not bond_terms:
            return atom_names

        generic_to_mol2 = cls._map_generic_itp_atoms_to_mol2(atom_names, bond_terms, structure_file)
        if not generic_to_mol2:
            return atom_names

        mol2_names = cls._read_mol2_atom_names(structure_file)
        remapped = {}
        for itp_idx, atom_name in atom_names.items():
            mol2_idx = generic_to_mol2.get(int(itp_idx))
            remapped[itp_idx] = mol2_names.get(mol2_idx, atom_name)
        return remapped

    @staticmethod
    def _read_mol2_atom_names(mol2_file: str) -> Dict[int, str]:
        names: Dict[int, str] = {}
        with open(mol2_file, "r") as handle:
            in_atoms = False
            for line in handle:
                stripped = line.strip()
                if stripped.startswith("@<TRIPOS>ATOM"):
                    in_atoms = True
                    continue
                if stripped.startswith("@<TRIPOS>") and in_atoms:
                    break
                if not in_atoms or not stripped:
                    continue

                parts = stripped.split()
                if len(parts) < 2:
                    continue
                try:
                    names[int(parts[0])] = parts[1]
                except ValueError:
                    continue
        return names

    @staticmethod
    def _read_pdb_atom_names(pdb_file: str) -> Dict[int, str]:
        names: Dict[int, str] = {}
        with open(pdb_file, "r") as handle:
            for line in handle:
                if not (line.startswith("ATOM") or line.startswith("HETATM")):
                    continue
                try:
                    atom_index = int(line[6:11].strip())
                except ValueError:
                    continue
                atom_name = line[12:16].strip()
                if atom_name:
                    names[atom_index] = atom_name
        return names

    @staticmethod
    def _parse_mol2_bonds(mol2_file: str) -> List[Tuple[int, int]]:
        bonds: List[Tuple[int, int]] = []
        with open(mol2_file, "r") as handle:
            in_bonds = False
            for line in handle:
                stripped = line.strip()
                if stripped.startswith("@<TRIPOS>BOND"):
                    in_bonds = True
                    continue
                if stripped.startswith("@<TRIPOS>") and in_bonds:
                    break
                if not in_bonds or not stripped:
                    continue

                parts = stripped.split()
                if len(parts) < 4:
                    continue
                try:
                    bonds.append((int(parts[1]), int(parts[2])))
                except ValueError:
                    continue
        return bonds

    @classmethod
    def _map_generic_itp_atoms_to_mol2(
        cls, atom_names: Dict[int, str], bond_terms: List[InteractionTerm], mol2_file: str
    ) -> Optional[Dict[int, int]]:
        try:
            import networkx as nx
        except Exception:
            return None

        itp_graph = nx.Graph()
        for idx in atom_names:
            itp_graph.add_node(int(idx))
        for term in bond_terms:
            ai, aj = int(term.atoms[0]), int(term.atoms[1])
            itp_graph.add_edge(ai, aj)
        for node in itp_graph.nodes:
            itp_graph.nodes[node]["degree"] = itp_graph.degree[node]

        mol2_names = cls._read_mol2_atom_names(mol2_file)
        mol2_bonds = cls._parse_mol2_bonds(mol2_file)
        if not mol2_names or not mol2_bonds:
            return None

        mol2_graph = nx.Graph()
        for idx in mol2_names:
            mol2_graph.add_node(int(idx))
        for ai, aj in mol2_bonds:
            mol2_graph.add_edge(ai, aj)
        for node in mol2_graph.nodes:
            mol2_graph.nodes[node]["degree"] = mol2_graph.degree[node]

        matcher = nx.algorithms.isomorphism.GraphMatcher(
            itp_graph,
            mol2_graph,
            node_match=lambda a, b: a.get("degree") == b.get("degree"),
        )
        if not matcher.is_isomorphic():
            return None

        mapping = {int(itp_idx): int(mol2_idx) for itp_idx, mol2_idx in matcher.mapping.items()}
        if len(mapping) != len(atom_names):
            return None
        return mapping

    @classmethod
    def _merge_section_terms(
        cls,
        section: str,
        terms_a: List[InteractionTerm],
        terms_b: List[InteractionTerm],
        atom_names_a: Dict[int, str],
        atom_names_b: Dict[int, str],
        index_map_a: Optional[Dict[int, int]] = None,
        index_map_b: Optional[Dict[int, int]] = None,
        name_map_a: Optional[Dict[Tuple[str, str], int]] = None,
        name_map_b: Optional[Dict[Tuple[str, str], int]] = None,
        dummy_in_a: Optional[set] = None,
        dummy_in_b: Optional[set] = None,
        atom_types_a: Optional[Dict[int, str]] = None,
        atom_types_b: Optional[Dict[int, str]] = None,
        atom_types_a_hybrid: Optional[Dict[int, str]] = None,
        atom_types_b_hybrid: Optional[Dict[int, str]] = None,
    ) -> List[Dict]:
        """Merge A/B section terms into hybrid interaction lines."""
        merged: Dict[Tuple, Dict[str, Optional[InteractionTerm]]] = {}

        def add_terms(
            state: str,
            terms: List[InteractionTerm],
            atom_names: Dict[int, str],
            atom_types: Optional[Dict[int, str]],
            index_map: Optional[Dict[int, int]],
            name_map: Optional[Dict[Tuple[str, str], int]],
        ) -> None:
            type_index_map: Dict[str, List[int]] = {}
            if name_map is not None:
                for (mapped_type, _mapped_name), hybrid_idx in name_map.items():
                    type_index_map.setdefault(mapped_type, []).append(hybrid_idx)

            for term in terms:
                hybrid_atoms = []
                for index in term.atoms:
                    if index_map is not None:
                        # Use direct index mapping (preferred)
                        if index not in index_map:
                            hybrid_atoms = []
                            break
                        hybrid_atoms.append(index_map[index])
                    else:
                        # Use name+type mapping (fallback)
                        if not atom_types or name_map is None:
                            hybrid_atoms = []
                            break
                        atom_name = atom_names.get(index)
                        atom_type = atom_types.get(index)
                        if not atom_name or not atom_type:
                            hybrid_atoms = []
                            break
                        key = (atom_type, atom_name)
                        hybrid_idx = name_map.get(key)
                        if hybrid_idx is None:
                            # Generic force fields such as OPLS may rename source ITP atoms
                            # to generator-local labels (C01/H07/...) while the hybrid ITP
                            # keeps chemistry-aware names (C10/H7/...). If the atom type is
                            # unique in the hybrid state, fall back to type-only matching.
                            candidates = type_index_map.get(atom_type, [])
                            if len(candidates) == 1:
                                hybrid_idx = candidates[0]
                        if hybrid_idx is None:
                            hybrid_atoms = []
                            break
                        hybrid_atoms.append(hybrid_idx)
                if not hybrid_atoms:
                    continue

                canonical_atoms = cls._canonicalize_atoms(section, tuple(hybrid_atoms))
                key = (
                    canonical_atoms,
                    term.funct,
                    cls._parameter_signature(section, term.funct, term.params),
                )
                entry = merged.setdefault(key, {"A": None, "B": None})
                entry[state] = InteractionTerm(atoms=canonical_atoms, funct=term.funct, params=list(term.params))

        add_terms("A", terms_a, atom_names_a, atom_types_a, index_map_a, name_map_a)
        add_terms("B", terms_b, atom_names_b, atom_types_b, index_map_b, name_map_b)

        output: List[Dict] = []
        for key in sorted(merged, key=lambda item: item[0]):
            term_a = merged[key]["A"]
            term_b = merged[key]["B"]
            canonical_atoms, funct, _ = key

            # CRITICAL FIX: Validate no self-bonds exist
            # Self-bonds occur when both atoms in a bond have the same index (e.g., 48-48)
            # This is caused by incorrect atom name mapping in _build_state_name_maps
            if section == "bonds" and len(canonical_atoms) == 2:
                if canonical_atoms[0] == canonical_atoms[1]:
                    import sys

                    print(
                        f"ERROR: Self-bond detected in hybrid topology: {canonical_atoms[0]}-{canonical_atoms[1]}",
                        file=sys.stderr,
                    )
                    print(f"This indicates a bug in atom name mapping. Please report this issue.", file=sys.stderr)
                    print(f"Term A: {term_a}", file=sys.stderr)
                    print(f"Term B: {term_b}", file=sys.stderr)
                    continue  # Skip self-bonds to prevent grompp failure

            if section == "pairs":
                output.append({"atoms": canonical_atoms, "funct": funct})
                continue

            has_dummy_in_a = bool(dummy_in_a and set(canonical_atoms) & dummy_in_a)
            has_dummy_in_b = bool(dummy_in_b and set(canonical_atoms) & dummy_in_b)

            if term_a is not None:
                params_a = list(term_a.params)
                # Zero force constant if any atom is dummy in state A (undefined geometry)
                if has_dummy_in_a and section in {"angles", "dihedrals", "impropers"}:
                    params_a = cls._zeroize_params(section, funct, params_a)
            else:
                params_a = (
                    list(term_b.params)
                    if has_dummy_in_a
                    else cls._zeroize_params(  # type: ignore[union-attr]
                        section, funct, list(term_b.params)
                    )
                )

            if term_b is not None:
                params_b = list(term_b.params)
                # Zero force constant if any atom is dummy in state B (undefined geometry)
                if has_dummy_in_b and section in {"angles", "dihedrals", "impropers"}:
                    params_b = cls._zeroize_params(section, funct, params_b)
            else:
                params_b = (
                    list(term_a.params)
                    if has_dummy_in_b
                    else cls._zeroize_params(  # type: ignore[union-attr]
                        section, funct, list(term_a.params)
                    )
                )

            # Special handling for CHARMM bonds/angles/dihedrals with atom type changes.
            # Only synthesize explicit zero parameters when a term is missing parameters
            # altogether; if both states already carry explicit parameters, keep them.
            if section in {"bonds", "angles", "dihedrals"} and atom_types_a_hybrid and atom_types_b_hybrid:
                if cls._has_type_changes(canonical_atoms, atom_types_a_hybrid, atom_types_b_hybrid):
                    needs_explicit_params = not params_a or not params_b
                    if not needs_explicit_params:
                        output.append(
                            {
                                "atoms": canonical_atoms,
                                "funct": funct,
                                "params_a": params_a,
                                "params_b": params_b,
                            }
                        )
                        continue

                    # For CHARMM-style terms written without explicit parameters,
                    # add explicit zero parameters to avoid GROMACS perturbation errors.
                    if section == "bonds":
                        # funct 1: b0, kb
                        if not params_a:
                            params_a = ["0.0", "0.0"]
                        else:
                            params_a = cls._zeroize_params(section, funct, params_a)
                        if not params_b:
                            params_b = ["0.0", "0.0"]
                        else:
                            params_b = cls._zeroize_params(section, funct, params_b)
                    elif section == "angles":
                        # funct 5: theta0, cth, ub0, cub (Urey-Bradley)
                        if not params_a:
                            params_a = ["0.0", "0.0", "0.0", "0.0"]
                        else:
                            params_a = cls._zeroize_params(section, funct, params_a)
                        if not params_b:
                            params_b = ["0.0", "0.0", "0.0", "0.0"]
                        else:
                            params_b = cls._zeroize_params(section, funct, params_b)
                    elif section == "dihedrals":
                        # funct 9: phi0, cp, mult
                        if not params_a:
                            params_a = ["0.0", "0.0", "1"]
                        else:
                            params_a = cls._zeroize_params(section, funct, params_a)
                        if not params_b:
                            params_b = ["0.0", "0.0", "1"]
                        else:
                            params_b = cls._zeroize_params(section, funct, params_b)

            output.append(
                {
                    "atoms": canonical_atoms,
                    "funct": funct,
                    "params_a": params_a,
                    "params_b": params_b,
                }
            )

        return output

    @staticmethod
    def _canonicalize_atoms(section: str, atoms: Tuple[int, ...]) -> Tuple[int, ...]:
        """Canonicalize interaction atom order for A/B matching."""
        if section in {"bonds", "pairs"}:
            return tuple(sorted(atoms))
        if section == "angles":
            return atoms if atoms[0] <= atoms[2] else atoms[::-1]
        return atoms if atoms <= atoms[::-1] else atoms[::-1]

    @staticmethod
    def _has_type_changes(atoms: Tuple[int, ...], atom_types_a: Dict[int, str], atom_types_b: Dict[int, str]) -> bool:
        """Check if any atoms in the interaction have different types in A vs B states."""
        for atom_id in atoms:
            type_a = atom_types_a.get(atom_id)
            type_b = atom_types_b.get(atom_id)
            if type_a and type_b and type_a != type_b:
                return True
        return False

    @staticmethod
    def _remap_atom_types_to_hybrid(
        source_atom_types: Dict[int, str], source_atom_names: Dict[int, str], name_map: Dict[str, int]
    ) -> Dict[int, str]:
        """
        Remap atom types from source ligand IDs to hybrid IDs.

        Parameters
        ----------
        source_atom_types : Dict[int, str]
            Atom types indexed by source ligand atom IDs
        source_atom_names : Dict[int, str]
            Atom names indexed by source ligand atom IDs
        name_map : Dict[str, int]
            Mapping from atom names to hybrid IDs

        Returns
        -------
        Dict[int, str]
            Atom types indexed by hybrid atom IDs
        """
        hybrid_atom_types = {}
        for source_id, atom_type in source_atom_types.items():
            atom_name = source_atom_names.get(source_id)
            if atom_name and atom_name in name_map:
                hybrid_id = name_map[atom_name]
                hybrid_atom_types[hybrid_id] = atom_type
        return hybrid_atom_types

    @staticmethod
    def _remap_atom_types_to_hybrid_by_index(
        source_atom_types: Dict[int, str], index_map: Dict[int, int]
    ) -> Dict[int, str]:
        """
        Remap atom types from source ligand IDs to hybrid IDs using direct index mapping.

        Parameters
        ----------
        source_atom_types : Dict[int, str]
            Atom types indexed by source ligand atom IDs
        index_map : Dict[int, int]
            Mapping from source atom indices to hybrid atom indices

        Returns
        -------
        Dict[int, str]
            Atom types indexed by hybrid atom IDs
        """
        hybrid_atom_types = {}
        for source_id, atom_type in source_atom_types.items():
            if source_id in index_map:
                hybrid_id = index_map[source_id]
                hybrid_atom_types[hybrid_id] = atom_type
        return hybrid_atom_types

    @staticmethod
    def _parameter_signature(section: str, funct: int, params: List[str]) -> Tuple[str, ...]:
        """
        Signature used to pair A/B terms whose non-perturbable identity must
        remain the same.
        """
        if section in {"dihedrals", "impropers"} and funct in {1, 4, 9} and len(params) >= 3:
            return (params[-1],)
        return tuple()

    @classmethod
    def _zeroize_params(cls, section: str, funct: int, params: List[str]) -> List[str]:
        """Generate a zero-force counterpart for terms missing in one state."""
        if not params:
            return []

        zero = list(params)

        if section == "bonds":
            if len(zero) >= 1:
                zero[0] = "0.000000"
            if len(zero) >= 2:
                zero[1] = "0.000000"
            return zero

        if section == "angles":
            # Zero angle force constant for dummy state — angles involving dummy atoms
            # can have undefined geometry (e.g. two H's at same position), causing huge forces.
            if len(zero) >= 2:
                zero[1] = "0.000000"
            return zero

        if section in {"dihedrals", "impropers"}:
            if funct in {1, 4, 9} and len(zero) >= 3:
                zero[1] = "0.000000"
                return zero
            if funct == 3:
                return ["0.000000" for _ in zero]
            for i in range(len(zero)):
                if cls._looks_like_float(zero[i]):
                    zero[i] = "0.000000"
            return zero

        for i in range(len(zero)):
            if cls._looks_like_float(zero[i]):
                zero[i] = "0.000000"
        return zero

    @staticmethod
    def _looks_like_float(value: str) -> bool:
        try:
            float(value)
        except ValueError:
            return False
        return True
