#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""GROMACS MDP helpers for PRISM-FEP."""

import json
from pathlib import Path
from typing import Dict, Optional, List, Tuple

FEP_PROD_MDP = """
; FEP Production MDP - Generated by PRISM-FEP
; Date: {date}
;
; This MDP file is configured for alchemical free energy perturbation
; calculations using GROMACS coupled-topology formalism.
;

include = -I. -I../mdps

; Integrator
integrator  = md
dt          = {dt}
nsteps      = {nsteps}

; Output
nstxout     = 5000
nstvout     = 5000
nstenergy   = {nstenergy}
nstlog      = {nstlog}
nstxout-compressed = {nstxout_compressed}

; Free energy parameters
free-energy              = yes
init-lambda-state        = {init_lambda_state}
delta-lambda             = 0
calc-lambda-neighbors    = 1
nstdhdl                  = {nstdhdl}
separate-dhdl-file       = yes

; Lambda schedules (strategy: {strategy})
coul-lambdas             = {coul_lambdas}
vdw-lambdas              = {vdw_lambdas}
bonded-lambdas           = {bonded_lambdas}
mass-lambdas             = {mass_lambdas}

; Soft-core parameters (avoid singularities)
sc-alpha                 = {sc_alpha}
sc-power                 = 1
sc-sigma                 = {sc_sigma}
sc-coul                  = yes

; NOTE: couple-moltype is NOT used because the hybrid topology
; already defines typeB/chargeB in the ITP file

; Nonbonded settings
cutoff-scheme   = Verlet
ns_type         = grid
nstlist         = 200  ; Optimized for multi-GPU with PME (matching bound performance)
rcoulomb        = {rcoulomb}
rvdw            = {rvdw}
table-extension = 2.0

; For dual-topology FEP, state A and state B atoms can have large separations.
; The table extension ensures the lookup table covers these long-range interactions.

; Temperature coupling
tcoupl          = {tcoupl}
tc-grps         = System
tau-t           = {tau_t}
ref-t           = {temp}

; Pressure coupling
pcoupl          = {pcoupl}
pcoupltype      = {pcoupltype}
tau-p           = {tau_p}
ref-p           = {pressure}
compressibility = {compressibility}

; Electrostatics
coulombtype     = {coulombtype}
pme_order       = {pme_order}
fourierspacing  = {fourierspacing}

; Van der Waals
vdwtype         = Cut-off
DispCorr        = EnerPres

; Periodic boundary conditions
pbc             = xyz

; Constraints
; For hybrid topologies, use standard constraints with increased LINCS accuracy
constraints             = {constraints_type}
constraint-algorithm    = {constraints_algorithm}
lincs-order             = 6
lincs-iter              = 2
lincs-warnangle         = 30
"""


def _locate_hybrid_itp(output_path: Path) -> Optional[Path]:
    """Resolve the hybrid topology relative to a leg mdps directory."""
    candidates = [
        output_path.parent.parent / "common" / "hybrid" / "hybrid.itp",
        output_path.parent.parent.parent / "common" / "hybrid" / "hybrid.itp",
        output_path.parent.parent.parent.parent / "common" / "hybrid" / "hybrid.itp",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None


def _detect_hybrid_runtime_guard(output_path: Path) -> Tuple[bool, int]:
    """
    Detect hybrid topologies that contain zeroized hydrogen bonds in one state.

    Such topologies cannot be safely used with `constraints = h-bonds` during
    early equilibration, because LINCS sees 0-length perturbed H-bonds at step 0.

    Returns
    -------
    tuple[bool, int]
        `(needs_unconstrained_runtime, zeroized_h_bond_count)`
    """
    hybrid_itp = _locate_hybrid_itp(output_path)
    if hybrid_itp is None:
        return False, 0

    atoms: Dict[int, str] = {}
    section = None
    zeroized_h_bonds = 0
    for raw_line in hybrid_itp.read_text().splitlines():
        line = raw_line.split(";", 1)[0].strip()
        if not line:
            continue
        if line.startswith("["):
            section = line.strip("[] ").strip().lower()
            continue

        parts = line.split()
        if section == "atoms" and len(parts) >= 5:
            atoms[int(parts[0])] = parts[4]
            continue
        if section != "bonds" or len(parts) < 7:
            continue

        ai = int(parts[0])
        aj = int(parts[1])
        r_a = float(parts[3])
        k_a = float(parts[4])
        r_b = float(parts[5])
        k_b = float(parts[6])
        zeroized_state = (r_a == 0.0 and k_a == 0.0) or (r_b == 0.0 and k_b == 0.0)
        if not zeroized_state:
            continue
        if atoms.get(ai, "").startswith("H") or atoms.get(aj, "").startswith("H"):
            zeroized_h_bonds += 1

    return zeroized_h_bonds > 0, zeroized_h_bonds


def write_fep_mdps(
    output_dir: str,
    lambda_strategy: str = "decoupled",
    lambda_distribution: str = "nonlinear",
    quadratic_exponent: float = 2.0,
    lambda_windows: int = 32,
    coul_windows: int = 12,
    vdw_windows: int = 20,
    custom_coul_lambdas: Optional[List[float]] = None,
    custom_vdw_lambdas: Optional[List[float]] = None,
    soft_core_alpha: float = 0.5,
    soft_core_sigma: float = 0.3,
    config: Optional[Dict] = None,
    leg_name: str = "fep",
):
    """
    Write FEP MDP files for all lambda windows

    Parameters
    ----------
    output_dir : str
        Output directory for MDP files
    lambda_strategy : str, optional
        Lambda strategy: 'coupled', 'decoupled', or 'custom' (default: 'decoupled')
    lambda_distribution : str, optional
        Distribution type: 'linear', 'nonlinear', or 'quadratic' (default: 'nonlinear')
    quadratic_exponent : float, optional
        Endpoint-bias exponent used when ``lambda_distribution='quadratic'`` (default: 2.0)
    lambda_windows : int, optional
        Total number of lambda windows for coupled mode (default: 32)
    coul_windows : int, optional
        Number of windows for electrostatics stage in decoupled mode (default: 12)
    vdw_windows : int, optional
        Number of windows for VDW stage in decoupled mode (default: 20)
    custom_coul_lambdas : List[float], optional
        Custom coulomb lambda array for custom strategy
    custom_vdw_lambdas : List[float], optional
        Custom VDW lambda array for custom strategy
    soft_core_alpha : float, optional
        Soft-core alpha parameter (default: 0.5)
    soft_core_sigma : float, optional
        Soft-core sigma parameter (default: 0.3)
    config : dict, optional
        Configuration dictionary with simulation parameters
    leg_name : str, optional
        Name of the FEP leg (default: "fep")
    """
    from prism.utils.config import ConfigurationManager

    config = config or {}
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # Load PRISM default configuration for MDP settings
    config_manager = ConfigurationManager()
    prism_config = config_manager.config

    # Get simulation parameters (use FEP config if provided, otherwise PRISM defaults)
    sim_cfg = config.get("simulation", {})
    fep_cfg = config.get("fep", {})
    lambda_cfg = config.get("lambda", {})

    # Override lambda parameters from config if provided (only if still at defaults)
    if quadratic_exponent == 2.0 and "quadratic_exponent" in lambda_cfg:
        quadratic_exponent = lambda_cfg["quadratic_exponent"]

    if fep_cfg:
        # Only override if parameters are still at default values
        if lambda_windows == 32 and "lambda_windows" in fep_cfg:
            lambda_windows = fep_cfg["lambda_windows"]
        if coul_windows == 12 and "coul_windows" in fep_cfg:
            coul_windows = fep_cfg["coul_windows"]
        if vdw_windows == 20 and "vdw_windows" in fep_cfg:
            vdw_windows = fep_cfg["vdw_windows"]
        if soft_core_alpha == 0.5 and "soft_core_alpha" in fep_cfg:
            soft_core_alpha = fep_cfg["soft_core_alpha"]
        if soft_core_sigma == 0.3 and "soft_core_sigma" in fep_cfg:
            soft_core_sigma = fep_cfg["soft_core_sigma"]

    # For decoupled strategy, if total_windows is customized (not default 32),
    # scale coul_windows and vdw_windows proportionally
    if lambda_strategy == "decoupled" and lambda_windows != 32:
        # Default ratio: 12:20 = 3:5 (coul:vdw)
        default_total = 32
        coul_ratio = coul_windows / default_total
        vdw_ratio = vdw_windows / default_total

        # Scale to target total_windows
        coul_windows = max(1, int(lambda_windows * coul_ratio))
        vdw_windows = max(1, lambda_windows - coul_windows)  # Ensure exact sum

        print(f"  📊 Lambda windows: {lambda_windows} total → {coul_windows} coul + {vdw_windows} vdw")

    # Temperature and pressure
    temp = sim_cfg.get("temperature", prism_config.get("md", {}).get("temperature", 310))
    pressure = sim_cfg.get("pressure", prism_config.get("md", {}).get("pressure", 1.0))
    dt = sim_cfg.get("dt", prism_config.get("md", {}).get("dt", 0.002))

    # Equilibration times
    nvt_ps = sim_cfg.get("equilibration_nvt_time_ps", 500)
    npt_ps = sim_cfg.get("equilibration_npt_time_ps", 500)
    npt_short_ps = sim_cfg.get("per_window_npt_time_ps", fep_cfg.get("per_window_npt_time_ps", 100))

    # Production time - prefer explicit simulation config, then legacy fep key
    prod_ns = sim_cfg.get("production_time_ns", fep_cfg.get("production_time_ns", 2.0))

    forcefield_info = config.get("forcefield", prism_config.get("forcefield", {}))
    if isinstance(forcefield_info, dict):
        forcefield_name = str(forcefield_info.get("name", ""))
    else:
        forcefield_name = str(forcefield_info)
    normalized_forcefield = forcefield_name.lower()
    uses_cmap_runtime_guard = "charmm" in normalized_forcefield or normalized_forcefield == "amber19sb"

    hybrid_needs_unconstrained_runtime, zeroized_h_bond_count = _detect_hybrid_runtime_guard(output_path)

    # CMAP force fields on hybrid systems are more fragile during the initial
    # constrained NVT/NPT equilibration. Zeroized perturbed H-bonds are even
    # more restrictive because they make LINCS constraints ill-defined at step 0.
    equil_dt = dt
    if uses_cmap_runtime_guard:
        equil_dt = min(equil_dt, 0.001)
    if hybrid_needs_unconstrained_runtime:
        equil_dt = min(equil_dt, 0.0005)

    # Get electrostatics and VDW parameters from PRISM config
    elec_cfg = prism_config.get("electrostatics", {})
    vdw_cfg = prism_config.get("vdw", {})
    # Use configured cutoff values, default to 1.0 nm if not specified
    rcoulomb = config.get("electrostatics", {}).get("rcoulomb", elec_cfg.get("rcoulomb", 1.0))
    rvdw = config.get("vdw", {}).get("rvdw", vdw_cfg.get("rvdw", 1.0))
    coulombtype = elec_cfg.get("coulombtype", "PME")
    pme_order = elec_cfg.get("pme_order", 4)
    fourierspacing = elec_cfg.get("fourierspacing", 0.16)

    # Get output parameters
    output_cfg = config.get("output", {})
    traj_interval = int(output_cfg.get("trajectory_interval_ps", 500) / dt)
    energy_interval = int(output_cfg.get("energy_interval_ps", 10) / dt)
    log_interval = int(output_cfg.get("log_interval_ps", 10) / dt)
    nstdhdl = int(output_cfg.get("nstdhdl", 100))
    if nstdhdl < 0:
        raise ValueError("output.nstdhdl must be >= 0")

    # Get constraints from PRISM config
    constraints_cfg = prism_config.get("constraints", {})
    configured_constraints = constraints_cfg.get("type")
    # Zeroized perturbed H-bonds make hydrogen-bond constraints ill-defined.
    # Only force unconstrained equilibration when the hybrid topology actually
    # contains such bonds; otherwise preserve the configured/default behavior.
    if hybrid_needs_unconstrained_runtime:
        constraints_type = "none"
    elif configured_constraints in (None, ""):
        constraints_type = prism_config.get("constraints", {}).get("type", "h-bonds") or "h-bonds"
    else:
        constraints_type = configured_constraints
    constraints_algorithm = constraints_cfg.get("algorithm", "lincs")

    schedule = _generate_lambda_schedule(
        strategy=lambda_strategy,
        distribution=lambda_distribution,
        quadratic_exponent=quadratic_exponent,
        total_windows=lambda_windows,
        coul_windows=coul_windows,
        vdw_windows=vdw_windows,
        custom_coul=custom_coul_lambdas,
        custom_vdw=custom_vdw_lambdas,
    )
    schedule["soft_core_alpha"] = soft_core_alpha
    schedule["soft_core_sigma"] = soft_core_sigma
    (output_path / "lambda_schedule.json").write_text(json.dumps(schedule, indent=2) + "\n")

    # Generate EM MDP (same as PRISM standard)
    # Support both "energy_minimization" and "simulation" config keys
    em_config = prism_config.get("energy_minimization", prism_config.get("simulation", {}))
    em_mdp = f"""; {leg_name} EM - Energy Minimization
integrator      = {em_config.get('integrator', 'steep')}
emtol           = {em_config.get('emtol', 1000.0)}
emstep          = {em_config.get('emstep', 0.01)}
nsteps          = 100000

; Output control
nstxout         = 500
nstvout         = 500
nstenergy       = 500
nstlog          = 500

; Neighbor searching
cutoff-scheme   = Verlet
ns_type         = grid
nstlist         = 10
rcoulomb        = {rcoulomb}
rvdw            = {rvdw}
table-extension = 2.0

; For dual-topology FEP, state A and state B atoms can have large separations.
; The table extension ensures the lookup table covers these long-range interactions.

; Electrostatics
coulombtype     = {coulombtype}
pme_order       = {pme_order}
fourierspacing  = {fourierspacing}

; VDW
vdwtype         = Cut-off
DispCorr        = EnerPres

; Temperature and pressure coupling are off during EM
tcoupl          = no
pcoupl          = no

; Periodic boundary conditions
pbc             = xyz

; Constraints
; For FEP hybrid topologies, constraints are disabled during EM because
; overlapping dual-topology atoms (state A and state B) cause LINCS failures.
; Energy minimization with bonded parameters will resolve the geometry.
constraints             = none
"""
    (output_path / "em.mdp").write_text(em_mdp)

    if hybrid_needs_unconstrained_runtime:
        constraints_comment = (
            f"; Hybrid topology contains {zeroized_h_bond_count} perturbed H-bond(s) "
            "with a zeroized state; disable constraints for stable startup."
        )
    else:
        constraints_comment = "; Use standard constraints for the initial equilibration."

    # Generate NVT MDP (same as PRISM standard)
    nvt_config = prism_config.get("nvt", {})
    nvt_mdp = f"""; {leg_name} NVT - NVT Equilibration
define              = -DPOSRES
integrator          = md
dt                  = {equil_dt}
nsteps              = {int(nvt_ps / equil_dt)}

; Output control
nstxout             = 0
nstvout             = 0
nstfout             = 0
nstlog              = {log_interval}
nstenergy           = {energy_interval}
nstxout-compressed  = 0

; Neighbor searching
cutoff-scheme       = Verlet
ns_type             = grid
nstlist             = 80  ; Increased from 10 for better GPU efficiency (reduces CPU-GPU sync)
rcoulomb            = {rcoulomb}
rvdw                = {rvdw}
table-extension     = 2.0

; For dual-topology FEP, state A and state B atoms can have large separations.
; The table extension ensures the lookup table covers these long-range interactions.

; Electrostatics
coulombtype         = {coulombtype}
pme_order           = {pme_order}
fourierspacing      = {fourierspacing}

; VDW
vdwtype             = Cut-off
DispCorr            = EnerPres

; Temperature coupling
tcoupl              = {nvt_config.get('tcoupl', 'V-rescale')}
tc-grps             = System
tau_t               = {nvt_config.get('tau_t', 0.1)}
ref_t               = {temp}

; Pressure coupling is off during NVT
pcoupl              = no

; Periodic boundary conditions
pbc                 = xyz

; Velocity generation
gen_vel             = yes
gen_temp            = {temp}
gen_seed            = -1

; Constraints
{constraints_comment}
constraints             = {constraints_type}
constraint-algorithm    = {constraints_algorithm}
lincs-order             = 6
lincs-iter              = 2
lincs-warnangle         = 30
"""
    (output_path / "nvt.mdp").write_text(nvt_mdp)

    # Generate NPT MDP (same as PRISM standard)
    npt_config = prism_config.get("npt", {})
    npt_mdp = f"""; {leg_name} NPT - NPT Equilibration
define              = -DPOSRES
integrator          = md
dt                  = {equil_dt}
nsteps              = {int(npt_ps / equil_dt)}

; Output control
nstxout             = 0
nstvout             = 0
nstfout             = 0
nstlog              = {log_interval}
nstenergy           = {energy_interval}
nstxout-compressed  = 0

; Neighbor searching
cutoff-scheme       = Verlet
ns_type             = grid
nstlist             = 80  ; Increased from 10 for better GPU efficiency (reduces CPU-GPU sync)
rcoulomb            = {rcoulomb}
rvdw                = {rvdw}
table-extension     = 2.0

; For dual-topology FEP, state A and state B atoms can have large separations.
; The table extension ensures the lookup table covers these long-range interactions.

; Electrostatics
coulombtype         = {coulombtype}
pme_order           = {pme_order}
fourierspacing      = {fourierspacing}

; VDW
vdwtype             = Cut-off
DispCorr            = EnerPres

; Temperature coupling
tcoupl              = {npt_config.get('tcoupl', 'V-rescale')}
tc-grps             = System
tau_t               = {npt_config.get('tau_t', 0.1)}
ref_t               = {temp}

; Pressure coupling
pcoupl              = {npt_config.get('pcoupl', 'C-rescale')}
pcoupltype          = {npt_config.get('pcoupltype', 'isotropic')}
tau_p               = {npt_config.get('tau_p', 2.0)}
ref_p               = {pressure}
compressibility     = {npt_config.get('compressibility', 4.5e-5)}

; Periodic boundary conditions
pbc                 = xyz

; Velocity generation
; Regenerate velocities for each lambda window instead of reusing the
; leg-level checkpoint. Dummy-state atoms can carry incompatible velocities
; when they are turned on at high lambda.
gen_vel             = yes
gen_temp            = {temp}
gen_seed            = -1

; Constraints
{constraints_comment}
constraints             = {constraints_type}
constraint-algorithm    = {constraints_algorithm}
lincs-order             = 6
lincs-iter              = 2
lincs-warnangle         = 30
"""
    (output_path / "npt.mdp").write_text(npt_mdp)

    # NOTE: NPT short MDPs are now generated per-window below (after lambda schedule is defined)
    # to include lambda-specific parameters for each window

    lambda_values = schedule["fep_lambdas"].split()
    prod_steps = int(prod_ns * 1000 / dt)

    # Get common MD parameters from PRISM config
    md_config = prism_config.get("md", {})
    tcoupl = md_config.get("tcoupl", "V-rescale")
    tau_t = md_config.get("tau_t", 0.5)
    pcoupl = md_config.get("pcoupl", "Parrinello-Rahman")
    pcoupltype = md_config.get("pcoupltype", "isotropic")
    tau_p = md_config.get("tau_p", 2.0)
    compressibility = md_config.get("compressibility", 4.5e-5)

    # Generate per-window lambda-specific relaxation MDPs.
    # A short EM stage is required before per-window MD for the end-state windows:
    # the bound leg can contain transformed B-state atoms that are geometrically
    # reasonable in the shared build structure, but still need lambda-specific
    # relaxation before constrained dynamics starts.
    for index, lambda_value in enumerate(lambda_values):
        em_short_mdp = f"""; {leg_name} EM Short - Per-Window Lambda Relaxation (Window {index:02d})
define              = -DPOSRES
integrator          = steep
emtol               = 1000.0
emstep              = 0.01
nsteps              = 20000

; Output control
nstxout             = 0
nstvout             = 0
nstfout             = 0
nstlog              = {log_interval}
nstenergy           = {energy_interval}
nstxout-compressed  = 0

; Free energy parameters
free-energy              = yes
init-lambda-state        = {index}
delta-lambda             = 0
calc-lambda-neighbors    = -1
nstdhdl                  = {nstdhdl}
separate-dhdl-file       = yes

; Lambda schedules (strategy: {schedule['strategy']})
coul-lambdas             = {schedule['coul_lambdas']}
vdw-lambdas              = {schedule['vdw_lambdas']}
bonded-lambdas           = {schedule['bonded_lambdas']}
mass-lambdas             = {schedule['mass_lambdas']}

; Soft-core parameters
sc-alpha                 = 0.5
sc-power                 = 1
sc-sigma                 = 0.5
sc-coul                  = yes

; Neighbor searching
cutoff-scheme       = Verlet
ns_type             = grid
nstlist             = 80
rcoulomb            = {rcoulomb}
rvdw                = {rvdw}
table-extension     = 2.0

; Electrostatics
coulombtype         = {coulombtype}
pme_order           = {pme_order}
fourierspacing      = {fourierspacing}

; VDW
vdwtype             = Cut-off
DispCorr            = EnerPres

; Periodic boundary conditions
pbc                 = xyz

; No thermostat/barostat during the lambda-specific minimization
tcoupl              = no
pcoupl              = no
gen_vel             = no

; Constraints
constraints             = none

; Lambda window {index}: nominal lambda = {lambda_value}
"""
        (output_path / f"em_short_{index:02d}.mdp").write_text(em_short_mdp)

        npt_short_mdp = f"""; {leg_name} NPT Short - Per-Window NPT Equilibration (Window {index:02d})
define              = -DPOSRES
integrator          = md
dt                  = 0.001  ; Reduced timestep for stability at intermediate lambda states
nsteps              = {int(npt_short_ps / 0.001)}

; Output control
nstxout             = 0
nstvout             = 0
nstfout             = 0
nstlog              = {log_interval}
nstenergy           = {energy_interval}
nstxout-compressed  = 0

; Free energy parameters
free-energy              = yes
init-lambda-state        = {index}
delta-lambda             = 0
calc-lambda-neighbors    = -1
nstdhdl                  = {nstdhdl}
separate-dhdl-file       = yes

; Lambda schedules (strategy: {schedule['strategy']})
coul-lambdas             = {schedule['coul_lambdas']}
vdw-lambdas              = {schedule['vdw_lambdas']}
bonded-lambdas           = {schedule['bonded_lambdas']}
mass-lambdas             = {schedule['mass_lambdas']}

; Soft-core parameters (avoid singularities)
; Increased sc-sigma for smoother VDW transformation and reduced clashes at intermediate lambda
sc-alpha                 = 0.5
sc-power                 = 1
sc-sigma                 = 0.5
sc-coul                  = yes

; NOTE: couple-moltype is NOT used because the hybrid topology
; already defines typeB/chargeB in the ITP file

; Neighbor searching
cutoff-scheme       = Verlet
ns_type             = grid
nstlist             = 80  ; Increased from 10 for better GPU efficiency (reduces CPU-GPU sync)
rcoulomb            = {rcoulomb}
rvdw                = {rvdw}
table-extension     = 2.0

; For dual-topology FEP, state A and state B atoms can have large separations.
; The table extension ensures the lookup table covers these long-range interactions.

; Electrostatics
coulombtype         = {coulombtype}
pme_order           = {pme_order}
fourierspacing      = {fourierspacing}

; VDW
vdwtype             = Cut-off
DispCorr            = EnerPres

; Temperature coupling
tcoupl              = {tcoupl}
tc-grps             = System
tau_t               = {tau_t}
ref_t               = {temp}

; Pressure coupling
; The box has already been equilibrated in the leg-level NPT stage.
; Per-window short relaxation only needs to relax lambda-specific contacts.
; Keeping pressure coupling on here can destabilize end-state windows.
pcoupl              = no
refcoord_scaling    = com

; Periodic boundary conditions
pbc                 = xyz

; Velocity generation
; Re-sample velocities for each lambda window to avoid carrying dummy-state
; velocities from the leg-level checkpoint into high-lambda windows.
gen_vel             = yes
gen_temp            = {temp}
gen_seed            = -1

; Constraints
; For hybrid topologies, use standard constraints with increased LINCS accuracy
constraints             = {constraints_type}
constraint-algorithm    = {constraints_algorithm}
lincs-order             = 6
lincs-iter              = 2
lincs-warnangle         = 30

; Lambda window {index}: nominal lambda = {lambda_value}
"""
        (output_path / f"npt_short_{index:02d}.mdp").write_text(npt_short_mdp)

    # Generate production MDPs for each lambda window
    for index, lambda_value in enumerate(lambda_values):
        prod_mdp = FEP_PROD_MDP.format(
            date="generated",
            dt=dt,
            nsteps=prod_steps,
            nstenergy=energy_interval,
            nstlog=log_interval,
            nstxout_compressed=traj_interval,
            nstdhdl=nstdhdl,
            init_lambda_state=index,
            strategy=schedule["strategy"],
            coul_lambdas=schedule["coul_lambdas"],
            vdw_lambdas=schedule["vdw_lambdas"],
            bonded_lambdas=schedule["bonded_lambdas"],
            mass_lambdas=schedule["mass_lambdas"],
            sc_alpha=soft_core_alpha,
            sc_sigma=soft_core_sigma,
            rcoulomb=rcoulomb,
            rvdw=rvdw,
            coulombtype=coulombtype,
            pme_order=pme_order,
            fourierspacing=fourierspacing,
            tcoupl=tcoupl,
            tau_t=tau_t,
            temp=temp,
            pcoupl=pcoupl,
            pcoupltype=pcoupltype,
            tau_p=tau_p,
            pressure=pressure,
            compressibility=compressibility,
            constraints_type=constraints_type,
            constraints_algorithm=constraints_algorithm,
        )
        prod_mdp += f"\n; Lambda window {index}: nominal lambda = {lambda_value}\n"
        (output_path / f"prod_{index:02d}.mdp").write_text(prod_mdp)


def _generate_distribution(n_points: int, dist_type: str, quadratic_exponent: float = 2.0) -> List[float]:
    """
    Generate lambda distribution

    Parameters
    ----------
    n_points : int
        Number of lambda points
    dist_type : str
        Distribution type: 'linear', 'nonlinear', or 'quadratic'
    quadratic_exponent : float
        Endpoint-bias exponent for the quadratic family. Only used when
        ``dist_type='quadratic'``. ``2.0`` reproduces the historical behavior.

    Returns
    -------
    List[float]
        Lambda values from 0.0 to 1.0
    """
    import numpy as np

    if dist_type == "linear":
        return list(np.linspace(0.0, 1.0, n_points))

    elif dist_type == "nonlinear":
        # Reference distribution from tests/gxf/FEP/ref/gxf_gmx_mdp_re/prod.mdp (32 points)
        # Dense at endpoints to capture steep free energy changes
        ref_32 = [
            0.00,
            0.01,
            0.02,
            0.04,
            0.06,
            0.09,
            0.12,
            0.16,
            0.20,
            0.24,
            0.28,
            0.32,
            0.36,
            0.40,
            0.44,
            0.48,
            0.52,
            0.56,
            0.60,
            0.64,
            0.68,
            0.72,
            0.76,
            0.80,
            0.84,
            0.88,
            0.91,
            0.94,
            0.96,
            0.98,
            0.99,
            1.00,
        ]

        if n_points == 32:
            return ref_32
        elif n_points < 32:
            # Subsample from ref_32
            indices = np.linspace(0, 31, n_points, dtype=int)
            return [ref_32[i] for i in indices]
        else:
            # Interpolate to more points
            x_ref = np.linspace(0, 1, 32)
            x_new = np.linspace(0, 1, n_points)
            return list(np.interp(x_new, x_ref, ref_32))

    elif dist_type == "quadratic":
        if quadratic_exponent < 1.0:
            raise ValueError("quadratic_exponent must be >= 1.0")

        # Power-law endpoint-biased distribution. exponent=2.0 reproduces the
        # previous piecewise quadratic schedule and larger values concentrate
        # more points near the endpoints while making the midpoint sparser.
        x = np.linspace(0, 1, n_points)
        lambdas = []
        for val in x:
            if val <= 0.5:
                lambdas.append(0.5 * (2 * val) ** quadratic_exponent)
            else:
                lambdas.append(1 - 0.5 * (2 * (1 - val)) ** quadratic_exponent)
        return lambdas

    else:
        raise ValueError(f"Unknown distribution type: {dist_type}")


def _generate_lambda_schedule(
    strategy: str = "decoupled",
    distribution: str = "nonlinear",
    quadratic_exponent: float = 2.0,
    total_windows: int = 32,
    coul_windows: int = 12,
    vdw_windows: int = 20,
    custom_coul: Optional[List[float]] = None,
    custom_vdw: Optional[List[float]] = None,
) -> Dict[str, str]:
    """
    Generate lambda schedule for FEP calculations

    Parameters
    ----------
    strategy : str, optional
        Lambda strategy: 'coupled', 'decoupled', or 'custom' (default: 'decoupled')
    distribution : str, optional
        Distribution type: 'linear', 'nonlinear', or 'quadratic' (default: 'nonlinear')
    quadratic_exponent : float, optional
        Endpoint-bias exponent for the quadratic family (default: 2.0)
    total_windows : int, optional
        Total number of lambda windows for coupled mode (default: 32)
    coul_windows : int, optional
        Number of windows for electrostatics stage in decoupled mode (default: 12)
    vdw_windows : int, optional
        Number of windows for VDW stage in decoupled mode (default: 20)
    custom_coul : List[float], optional
        Custom coulomb lambda array
    custom_vdw : List[float], optional
        Custom VDW lambda array

    Returns
    -------
    Dict[str, str]
        Dictionary containing formatted lambda strings:
        - fep_lambdas: Main lambda schedule
        - coul_lambdas: Coulomb lambda schedule
        - vdw_lambdas: VDW lambda schedule
        - bonded_lambdas: Bonded interactions lambda schedule
        - mass_lambdas: Mass lambda schedule
        - strategy: Strategy used
        - n_windows: Total number of windows
    """
    if strategy == "custom":
        # Use custom lambda arrays
        if custom_coul is None or custom_vdw is None:
            raise ValueError("custom strategy requires both custom_coul and custom_vdw")

        coul_lambdas = custom_coul
        vdw_lambdas = custom_vdw
        n_windows = max(len(coul_lambdas), len(vdw_lambdas))

        # Pad shorter array with final value
        if len(coul_lambdas) < n_windows:
            coul_lambdas = list(coul_lambdas) + [coul_lambdas[-1]] * (n_windows - len(coul_lambdas))
        if len(vdw_lambdas) < n_windows:
            vdw_lambdas = list(vdw_lambdas) + [vdw_lambdas[-1]] * (n_windows - len(vdw_lambdas))

    elif strategy == "coupled":
        # All lambdas change together from 0 to 1
        lambdas = _generate_distribution(total_windows, distribution, quadratic_exponent=quadratic_exponent)
        coul_lambdas = lambdas
        vdw_lambdas = lambdas
        n_windows = total_windows

    elif strategy == "decoupled":
        # Stage 1: Turn off electrostatics (coul 0→1, vdw=0)
        # Stage 2: Turn off VDW (coul=1, vdw 0→1)
        coul_stage = _generate_distribution(coul_windows, distribution, quadratic_exponent=quadratic_exponent)
        vdw_stage = _generate_distribution(vdw_windows, distribution, quadratic_exponent=quadratic_exponent)

        # Stage 1: coul changes, vdw stays at 0
        coul_lambdas = coul_stage + [1.0] * vdw_windows
        vdw_lambdas = [0.0] * coul_windows + vdw_stage

        n_windows = coul_windows + vdw_windows

    else:
        raise ValueError(f"Unknown strategy: {strategy}. Use 'coupled', 'decoupled', or 'custom'")

    # Bonded and mass lambdas follow the same schedule as coul (can be customized)
    bonded_lambdas = coul_lambdas
    mass_lambdas = coul_lambdas

    # Format as strings
    coul_lambdas_str = " ".join([f"{x:.2f}" for x in coul_lambdas])
    vdw_lambdas_str = " ".join([f"{x:.2f}" for x in vdw_lambdas])
    bonded_lambdas_str = " ".join([f"{x:.2f}" for x in bonded_lambdas])
    mass_lambdas_str = " ".join([f"{x:.2f}" for x in mass_lambdas])
    fep_lambdas_str = coul_lambdas_str  # Main lambda schedule

    return {
        "fep_lambdas": fep_lambdas_str,
        "coul_lambdas": coul_lambdas_str,
        "vdw_lambdas": vdw_lambdas_str,
        "bonded_lambdas": bonded_lambdas_str,
        "mass_lambdas": mass_lambdas_str,
        "strategy": strategy,
        "distribution": distribution,
        "quadratic_exponent": quadratic_exponent,
        "n_windows": n_windows,
    }
