#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Multi-Backend HTML Report Generator for FEP Analysis

Generates comprehensive HTML reports comparing multiple backends.
Includes tab-based backend switching, comparison plots, and per-backend detailed analysis.
"""

from pathlib import Path
from typing import Union, TYPE_CHECKING
from datetime import datetime

if TYPE_CHECKING:
    pass


class MultiBackendReportGenerator:
    """
    Generate HTML reports comparing multiple backends

    Creates comprehensive HTML reports with:
    - Tab-based backend switching
    - Comparison plots
    - Per-backend detailed analysis

    Parameters
    ----------
    all_results : list of dict
        List of result dictionaries from multiple backends
    template_style : str, optional
        Style preference: 'modern' (default) or 'minimal'

    Examples
    --------
    >>> results = [
    ...     {'backend': 'alchemlyb', 'estimator': 'TI', 'delta_g': -10.5, ...},
    ...     {'backend': 'alchemlyb', 'estimator': 'BAR', 'delta_g': -11.2, ...},
    ... ]
    >>> generator = MultiBackendReportGenerator(results)
    >>> html_path = generator.generate('comparison_report.html')
    """

    def __init__(self, all_results: list, template_style: str = "modern"):
        """
        Initialize multi-backend report generator

        Parameters
        ----------
        all_results : list of dict
            Results from multiple backends
        template_style : str
            'modern' or 'minimal' style
        """
        self.all_results = all_results
        self.template_style = template_style

    def generate(self, output_path: Union[str, Path]) -> Path:
        """
        Generate HTML report

        Parameters
        ----------
        output_path : str
            Path to output HTML file

        Returns
        -------
        Path
            Path to generated HTML file
        """
        html_content = self._generate_html()

        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, "w") as f:
            f.write(html_content)

        return output_path

    def _generate_html(self) -> str:
        """Generate complete HTML document with backend tabs"""

        # Load templates
        from .html import _load_template

        css_content = _load_template("styles.css")
        js_content = _load_template("script.js")

        # Build comparison table
        comparison_rows = ""
        for result in self.all_results:
            error_display = (
                f"± {result['delta_g_error']:.2f}" if result["delta_g_error"] == result["delta_g_error"] else "N/A"
            )
            comparison_rows += f"""
                    <tr>
                        <td>{result["name"]}</td>
                        <td class="value">{result["delta_g"]:.2f}</td>
                        <td class="value">{error_display}</td>
                        <td class="value">{result["delta_g_bound"]:.2f}</td>
                        <td class="value">{result["delta_g_unbound"]:.2f}</td>
                    </tr>
            """

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FEP Analysis - Multi-Backend Comparison</title>
    <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
    <style>
{css_content}
    </style>
    <script>
{js_content}
    </script>
</head>
<body>
    <div class="container">
        <header>
            <h1>🧪 FEP Analysis - Multi-Backend Comparison</h1>
            <div class="subtitle">
                Generated on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
            </div>
        </header>

        <div class="card">
            <h2>📊 Results Comparison</h2>
            <table>
                <thead>
                    <tr>
                        <th>Backend / Estimator</th>
                        <th>ΔG (kcal/mol)</th>
                        <th>Error (kcal/mol)</th>
                        <th>Bound Leg</th>
                        <th>Unbound Leg</th>
                    </tr>
                </thead>
                <tbody>
{comparison_rows}
                </tbody>
            </table>
        </div>

        <div class="footer">
            <p>Generated by PRISM FEP Analyzer</p>
            <p>{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
        </div>
    </div>
</body>
</html>
"""
        return html
