#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Membrane-specific GROMACS MDP generation.

Membrane simulations differ from soluble-protein runs in four crucial ways:

* **Semiisotropic pressure coupling** — the membrane plane (xy) and normal (z)
  are coupled separately so the bilayer can relax its area-per-lipid without the
  box collapsing. Isotropic coupling keeps the membrane under artificial tension.
* **Grouped thermostatting** — solute, membrane and solvent are coupled to
  separate v-rescale baths (never split ions from their solvent).
* **van-der-Waals treatment** — CHARMM36 lipids *require* a force-switch
  modifier (potential-based switching produces a spurious gel phase and a wrong
  area-per-lipid); AMBER/Lipid21 use a plain cutoff with dispersion correction.
* **Staged restraint release** — see below.

Why the staged protocol
-----------------------
A freshly PACKMOL-packed bilayer is *not* a relaxed structure: lipid tails are
interdigitated, headgroups sit at arbitrary depths and the protein-lipid
interface is full of near-contacts. Two things go wrong if such a system is
handed straight to unrestrained 2 fs dynamics:

1. The local geometry is bad enough that LINCS fails and the run dies.
2. Even when it survives, lipid tails flood into the protein interior and into
   crevices they would never reach on an equilibrated structure, permanently
   distorting the fold. A restraint that is released *after* the lipids have
   packed around the protein is the only cheap way to prevent this.

So the protein (and the lipid headgroups, which set the bilayer profile) are
held by position restraints that are released over three equilibration stages
while the integrator steps up from 1 fs to 2 fs:

    stage  dt      duration  restraints                       barostat
    em     --      --        none (relieve packing clashes)   none
    nvt    1 fs    250 ps    full   (protein BB+SC, lipids)   none
    npt    1 fs    500 ps    half   (protein BB+SC, lipids)   C-rescale
    npt2   2 fs      5 ns    weak   (protein backbone only)   C-rescale
    md     2 fs    user      none                             Parrinello-Rahman

The durations in that table are only a reading aid; ``_NVT_DURATION_PS`` /
``_NPT_DURATION_PS`` / ``_NPT2_DURATION_PS`` below are what the generator
actually uses, so change them there and update the table to match.

Restraints are expressed as ``define`` macros rather than as separate topologies
so that a *single* topology serves every stage; the matching ``#ifdef``-guarded
include files (``posre_solu.itp`` for ``-DPOSRES``, ``posre_memb.itp`` for
``-DPOSRES_LIPID``) are written by the membrane builder. The macro names below
are a fixed contract with those files.

The thermostat groups default to ``SOLU`` / ``MEMB`` / ``SOLV`` (an index file
with those groups is generated by the membrane builder).
"""

from __future__ import annotations

import math
import os
from typing import NamedTuple, Optional, Sequence

from .config import (
    DEFAULT_PRODUCTION_NS,
    MEMBRANE_EQUIL_TIMESTEP_PS,
    MEMBRANE_TIMESTEP_PS,
    membrane_production_steps,
)

__all__ = ["MEMBRANE_MDP_DIRNAME", "write_membrane_mdps"]

#: Subdirectory the membrane protocol is written to.  Deliberately *not*
#: ``mdps``: that directory belongs to the soluble generator
#: (:class:`prism.utils.mdp.MDPGenerator`), which owns the very same
#: ``em``/``nvt``/``npt``/``md`` stems.  Sharing it means two incompatible
#: protocols silently overwrite each other whenever both are built into one
#: output directory, and -- worse -- every generic consumer that resolves
#: ``<output_dir>/mdps/md.mdp`` (``prism.sim``, ``prism.core``, the soluble run
#: script) would hand a ``tc-grps = SOLU MEMB SOLV`` file to a ``grompp`` call
#: that passes no ``-n index.ndx``, which is fatal.  A separate name makes the
#: protocol identifiable from its path alone.
MEMBRANE_MDP_DIRNAME = "mdps_memb"

#: Wall-clock length of each equilibration stage, in ps.  Steps are derived from
#: these and the stage timestep so that changing a timestep constant keeps the
#: *physical* duration intact instead of silently halving/doubling it.
_NVT_DURATION_PS = 250.0
_NPT_DURATION_PS = 500.0
# Area per lipid is the SLOW variable here: box volume settles within a few
# hundred ps, so a protocol that looks converged after ~1 ns is watching the
# fast coordinate while the area is still drifting (Anezo et al. 2003 measure
# 5-25 ns for APL).  Production then switches to Parrinello-Rahman, which has no
# dissipation and oscillates if started away from equilibrium.  Published
# guidance spans 5-10 ns (GROMACS membrane how-to, AMBER Tutorial 16) to 100+ ns
# for multi-component bilayers (LiveCoMS membrane best practices, 2019); 5 ns is
# the low end, chosen so a default build stays affordable.  Multi-component or
# cholesterol-rich bilayers should extend this.
_NPT2_DURATION_PS = 5000.0

#: Restraint release schedule, as fractions of the caller-supplied "full"
#: force constants.  Two halvings-ish steps rather than one big drop: releasing
#: restraints in a single step re-introduces exactly the shock the protocol
#: exists to avoid.
_REDUCED_SCALE = 0.5
_WEAK_SCALE = 0.1


class _EquilStage(NamedTuple):
    """One stage of the staged restraint-release equilibration."""

    key: str  # returned dict key, also the .mdp file stem
    label: str  # stage name in the file header
    rationale: str  # WHY this stage exists (written into the .mdp)
    timestep_ps: float
    duration_ps: float
    barostat: str  # barostat name, or "no" for NVT
    gen_vel: bool
    fc_backbone: float
    fc_sidechain: float
    #: ``None`` leaves the lipids completely free (no ``-DPOSRES_LIPID``).
    fc_lipid: Optional[float]


#: PME reciprocal-space grid, shared by both lipid force fields.  Emitted
#: explicitly rather than left to GROMACS' 0.12 nm default: membranes are the
#: largest systems PRISM builds, so an implicitly *denser* FFT grid costs most
#: exactly here, and 0.16 nm at order 4 is what every soluble PRISM run already
#: uses (:mod:`prism.utils.mdp`).  Leaving it implicit made the two protocols
#: accidentally, rather than deliberately, different.
_PME_GRID = (
    "pme_order               = 4\n"
    "fourierspacing          = 0.16\n"
)


def _vdw_block(ff_family: str) -> str:
    """Return the vdW/electrostatics block appropriate for the lipid FF."""
    family = (ff_family or "").lower()
    if family not in {"amber", "charmm"}:
        raise ValueError(f"Unsupported membrane force-field family: {ff_family!r}")
    if family == "charmm":
        # CHARMM36 lipids: force-switch is mandatory.
        return (
            "cutoff-scheme           = Verlet\n"
            "coulombtype             = PME\n"
            "rcoulomb                = 1.2\n"
            f"{_PME_GRID}"
            "vdwtype                 = Cut-off\n"
            "vdw-modifier            = Force-switch\n"
            "rvdw-switch             = 1.0\n"
            "rvdw                    = 1.2\n"
            "rlist                   = 1.2\n"
            "DispCorr                = no\n"
        )
    # AMBER Lipid21 / Slipids
    return (
        "cutoff-scheme           = Verlet\n"
        "coulombtype             = PME\n"
        "rcoulomb                = 1.0\n"
        f"{_PME_GRID}"
        "vdwtype                 = Cut-off\n"
        "rvdw                    = 1.0\n"
        "DispCorr                = EnerPres\n"
    )


def _tcoupl_block(temperature: float, groups: Sequence[str]) -> str:
    grps = " ".join(groups)
    taus = " ".join(["1.0"] * len(groups))
    refs = " ".join([f"{temperature}"] * len(groups))
    # GROMACS treats '-' and '_' in option names interchangeably, but PRISM's own
    # readers do not: prism.utils.mdp.parse_mdp_file stores raw keys, and
    # prism.sim.openmmsim looks up 'ref_t'/'gen_vel'.  So the spelling here is
    # not cosmetic -- it follows prism.utils.mdp's mixed house style (underscores
    # for tau_t/ref_t/..., dashes for tc-grps/cutoff-scheme) so that membrane
    # .mdp files introspect the same as every other PRISM protocol.
    return (
        "tcoupl                  = V-rescale\n"
        f"tc-grps                 = {grps}\n"
        f"tau_t                   = {taus}\n"
        f"ref_t                   = {refs}\n"
    )


def _pcoupl_block(kind: str, *, restrained: bool = False) -> str:
    """Semiisotropic pressure coupling block. ``kind`` = barostat name or 'no'."""
    if kind == "no":
        return "pcoupl                  = no\n"
    # 1 bar is fixed rather than configurable, and the CLI refuses --pressure in
    # membrane mode for the same reason: the lipid force fields and the staged
    # protocol are validated at ambient pressure, and area-per-lipid -- the
    # observable the whole protocol exists to converge -- is only comparable to
    # published values there.
    block = (
        f"pcoupl                  = {kind}\n"
        "pcoupltype              = semiisotropic\n"
        "ref_p                   = 1.0     1.0\n"
        "compressibility         = 4.5e-5  4.5e-5\n"
        "tau_p                   = 5.0\n"
    )
    # refcoord_scaling only means anything when position restraints are active:
    # it tells grompp to scale the *reference* coordinates along with the box.
    # On an unrestrained stage there are no reference coordinates, so emitting
    # it is misleading noise -- hence it is tied to the restraint state.
    if restrained:
        block += "refcoord_scaling        = com\n"
    return block


def _fmt_fc(value: float) -> str:
    """Format a force constant for a ``-D`` macro.

    ``%g`` keeps user-supplied precision, but a bare ``1000`` reads like an
    integer once it has been pasted into the .itp; the trailing ``.0`` matches
    the soluble-protein protocol's output and keeps it obviously a float.
    """
    text = f"{value:g}"
    return text if ("." in text or "e" in text or "E" in text) else f"{text}.0"


def _define_line(
    fc_backbone: float,
    fc_sidechain: float,
    fc_lipid: Optional[float],
) -> str:
    """Build the ``define`` line for one restrained stage.

    Invariant: a force-constant macro is *only* emitted together with the macro
    that switches its restraint block on.  The .itp files reference
    ``POSRES_FC_BB`` / ``POSRES_FC_SC`` inside ``#ifdef POSRES`` and
    ``POSRES_FC_LIPID`` inside ``#ifdef POSRES_LIPID``; defining the guard
    without the force constant leaves an unsubstituted token in the topology and
    grompp dies, so the two always travel together.  Conversely a zero force
    constant is a legal "restrained by nothing" -- that is how the backbone-only
    stage frees the sidechains without dropping the macro grompp needs.
    """
    macros = [
        "-DPOSRES",
        f"-DPOSRES_FC_BB={_fmt_fc(fc_backbone)}",
        f"-DPOSRES_FC_SC={_fmt_fc(fc_sidechain)}",
    ]
    if fc_lipid is not None:
        macros.append("-DPOSRES_LIPID")
        macros.append(f"-DPOSRES_FC_LIPID={_fmt_fc(fc_lipid)}")
    return "define                  = " + " ".join(macros) + "\n"


def _genvel_block(gen_vel: bool, temperature: float) -> str:
    """Velocity-generation block.

    ``gen_temp``/``gen_seed`` are only emitted alongside ``gen_vel = yes``.
    GROMACS ignores them otherwise, but a continuation stage that still
    advertises a generation temperature reads as if it reheats the system, which
    is exactly the opposite of what it does.
    """
    if not gen_vel:
        return "gen_vel                 = no\n"
    return (
        "gen_vel                 = yes\n"
        f"gen_temp                = {temperature}\n"
        "gen_seed                = -1\n"
    )


def _nsteps(duration_ps: float, timestep_ps: float) -> int:
    """Steps needed to cover ``duration_ps`` at ``timestep_ps`` (at least one)."""
    return max(1, int(round(duration_ps / timestep_ps)))


# EM is deliberately *unrestrained*: its entire job is to relieve the atom
# overlaps PACKMOL leaves behind, and restraining the very atoms that are
# clashing is what turns a fixable clash into a LINCS failure downstream.
_EM = """; Membrane energy minimization (PRISM)
; Unrestrained: relieve PACKMOL packing clashes before any dynamics.
integrator              = steep
emtol                   = 1000.0
emstep                  = 0.01
nsteps                  = 50000
nstlist                 = 10
pbc                     = xyz
{vdw}"""

# No comm-grps here (nor in _MD), and that is deliberate rather than forgotten:
# the soluble protocol removes centre-of-mass motion per thermostat group, but
# doing that over SOLU/MEMB/SOLV lets the bilayer and the solvent drift against
# each other, a well-known source of bilayer artifacts.  Whole-system removal
# (the GROMACS default) is the correct choice for a membrane.
_EQ = """; Membrane {stage} equilibration (PRISM)
; {rationale}
; {duration_ps:g} ps at {timestep_fs:g} fs ({nsteps} steps).
{define}integrator              = md
dt                      = {timestep_ps}
nsteps                  = {nsteps}
nstxout-compressed      = 5000
nstlog                  = 5000
nstenergy               = 5000
continuation            = {cont}
constraint_algorithm    = lincs
constraints             = h-bonds
lincs_iter              = 1
lincs_order             = 4
pbc                     = xyz
{vdw}{tcoupl}{pcoupl}{genvel}"""

_MD = """; Membrane production MD (PRISM)
; Unrestrained -- every restraint has been released by the equilibration stages.
;
; DISCARD THE START OF THIS RUN. The preceding stages equilibrate box volume,
; which converges quickly, but area per lipid keeps drifting for far longer.
; Published protocols discard tens of ns here (CHARMM-GUI's own validation
; discarded 50 ns after a comparable equilibration). Check that area per lipid
; and box-xy have plateaued before treating any of this trajectory as sampling.
; Parrinello-Rahman is used from here on: it gives the correct ensemble but has
; no dissipation, so it will oscillate for a while if the box is still relaxing.
integrator              = md
dt                      = {timestep_ps}
nsteps                  = {nsteps}
nstxout-compressed      = 50000
nstlog                  = 50000
nstenergy               = 50000
continuation            = yes
constraint_algorithm    = lincs
constraints             = h-bonds
lincs_iter              = 1
lincs_order             = 4
pbc                     = xyz
{vdw}{tcoupl}{pcoupl}gen_vel                 = no
"""


def _require_force_constant(value, field_name: str) -> float:
    """Reject NaN/Inf/negative force constants before they reach the topology."""
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError(f"Membrane {field_name} must be a finite number.")
    number = float(value)
    if not math.isfinite(number) or number < 0:
        raise ValueError(f"Membrane {field_name} must be a non-negative finite value.")
    return number


def write_membrane_mdps(
    out_dir: str,
    temperature: float = 303.15,
    ff_family: str = "amber",
    tc_groups: Sequence[str] = ("SOLU", "MEMB", "SOLV"),
    production_ns: float = DEFAULT_PRODUCTION_NS,
    posres_fc_backbone: float = 1000.0,
    posres_fc_sidechain: float = 500.0,
    posres_fc_lipid: float = 1000.0,
) -> dict:
    """Write the staged membrane MDP protocol into ``out_dir/mdps_memb``.

    Stages: ``em`` -> ``nvt`` -> ``npt`` -> ``npt2`` -> ``md`` (see the module
    docstring for the physics). The three ``posres_fc_*`` arguments are the
    *full* restraint force constants in kJ/mol/nm^2, applied during NVT; the
    later stages scale them down (``_REDUCED_SCALE``, then ``_WEAK_SCALE``)
    before production runs unrestrained.

    Returns a mapping of stage -> file path, always containing at least the
    ``em``/``nvt``/``npt``/``md`` keys. Resolve the directory through
    :data:`MEMBRANE_MDP_DIRNAME` rather than hardcoding it.
    """
    if not math.isfinite(temperature) or temperature <= 0:
        raise ValueError("Membrane temperature must be a positive finite value.")
    nsteps_prod = membrane_production_steps(production_ns)
    if isinstance(tc_groups, (str, bytes)):
        raise TypeError("tc_groups must be a sequence of group names, not a string.")
    tc_groups = tuple(str(group).strip() for group in tc_groups)
    if not tc_groups or any(not group for group in tc_groups):
        raise ValueError("At least one non-empty thermostat group is required.")
    if len(set(tc_groups)) != len(tc_groups):
        raise ValueError("Thermostat group names must be unique.")
    fc_bb = _require_force_constant(posres_fc_backbone, "backbone restraint force constant")
    fc_sc = _require_force_constant(posres_fc_sidechain, "sidechain restraint force constant")
    fc_lip = _require_force_constant(posres_fc_lipid, "lipid restraint force constant")

    vdw = _vdw_block(ff_family)
    tcoupl = _tcoupl_block(temperature, tc_groups)

    # The restraint-release ladder.  Read top to bottom: the timestep grows only
    # once the restraints that make the previous timestep safe have done their
    # job, and the lipids are freed one stage before the protein backbone is.
    stages = (
        _EquilStage(
            key="nvt",
            label="NVT",
            rationale=(
                "Full restraints (protein backbone + sidechains, lipid headgroups); "
                "1 fs while the packed geometry is still poor."
            ),
            timestep_ps=MEMBRANE_EQUIL_TIMESTEP_PS,
            duration_ps=_NVT_DURATION_PS,
            barostat="no",
            gen_vel=True,
            fc_backbone=fc_bb,
            fc_sidechain=fc_sc,
            fc_lipid=fc_lip,
        ),
        _EquilStage(
            key="npt",
            label="NPT",
            rationale=(
                "Reduced restraints; the barostat now relaxes the area-per-lipid "
                "while the protein is still held near its input pose."
            ),
            timestep_ps=MEMBRANE_EQUIL_TIMESTEP_PS,
            duration_ps=_NPT_DURATION_PS,
            barostat="C-rescale",
            gen_vel=False,
            fc_backbone=fc_bb * _REDUCED_SCALE,
            fc_sidechain=fc_sc * _REDUCED_SCALE,
            fc_lipid=fc_lip * _REDUCED_SCALE,
        ),
        _EquilStage(
            key="npt2",
            label="NPT2",
            rationale=(
                "Weak backbone-only restraints at the production timestep: lipids "
                "and sidechains are free to pack against each other, the fold is not."
            ),
            timestep_ps=MEMBRANE_TIMESTEP_PS,
            duration_ps=_NPT2_DURATION_PS,
            barostat="C-rescale",
            gen_vel=False,
            fc_backbone=fc_bb * _WEAK_SCALE,
            # Sidechains released here, but the macro stays (see _define_line).
            fc_sidechain=0.0,
            fc_lipid=None,
        ),
    )

    mdp_dir = os.path.join(out_dir, MEMBRANE_MDP_DIRNAME)
    os.makedirs(mdp_dir, exist_ok=True)

    files = {}

    # EM (no temperature/pressure coupling, no restraints)
    files["em"] = os.path.join(mdp_dir, "em.mdp")
    with open(files["em"], "w") as fh:
        fh.write(_EM.format(vdw=vdw))

    for stage in stages:
        nsteps = _nsteps(stage.duration_ps, stage.timestep_ps)
        files[stage.key] = os.path.join(mdp_dir, f"{stage.key}.mdp")
        with open(files[stage.key], "w") as fh:
            fh.write(_EQ.format(
                stage=stage.label,
                rationale=stage.rationale,
                duration_ps=stage.duration_ps,
                timestep_fs=stage.timestep_ps * 1000,
                nsteps=nsteps,
                cont="no" if stage.gen_vel else "yes",
                vdw=vdw,
                tcoupl=tcoupl,
                # Every equilibration stage is restrained, so refcoord-scaling
                # belongs on each of them that also has a barostat.
                pcoupl=_pcoupl_block(stage.barostat, restrained=True),
                genvel=_genvel_block(stage.gen_vel, temperature),
                define=_define_line(stage.fc_backbone, stage.fc_sidechain, stage.fc_lipid),
                timestep_ps=f"{stage.timestep_ps:g}",
            ))

    # Production (Parrinello-Rahman, unrestrained -- so no define, and no
    # refcoord-scaling either).
    files["md"] = os.path.join(mdp_dir, "md.mdp")
    with open(files["md"], "w") as fh:
        fh.write(_MD.format(
            nsteps=nsteps_prod, vdw=vdw, tcoupl=tcoupl,
            pcoupl=_pcoupl_block("Parrinello-Rahman", restrained=False),
            timestep_ps=f"{MEMBRANE_TIMESTEP_PS:g}",
        ))

    return files
