#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Comprehensive unit tests for enhanced SwissParam ForceFieldGenerator
Tests RTF parsing, PRISM format generation, and error handling
"""

import pytest
import os
import sys
import tempfile
import shutil
from pathlib import Path
from unittest.mock import Mock, patch

# Add PRISM to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from prism.forcefield.swissparam import SwissParamForceFieldGenerator, MMFFForceFieldGenerator, MATCHForceFieldGenerator


class TestSwissParamRTFParsing:
    """Test RTF file parsing functionality"""

    @pytest.fixture
    def sample_rtf_file(self, tmp_path):
        """Create a sample RTF file for testing"""
        rtf_content = """* Test RTF file
MASS
BOND C1 C2
ANGLE C1 C2 C3
DIHEDRAL C1 C2 C3 C4

ATOM C1 CT 0.0
ATOM C2 CT 0.0
ATOM C3 CT 0.0
ATOM C4 CT 0.0
ATOM H1 HC 0.0
ATOM H2 HC 0.0

BOND C1 H1 C1 H2 C2 H1
ANGLE H1 C1 H2 C1 C2 H1
DIHEDRAL H1 C1 C2 H2
"""
        rtf_file = tmp_path / "test.rtf"
        rtf_file.write_text(rtf_content)
        return str(rtf_file)

    @pytest.fixture
    def sample_pdb_file(self, tmp_path):
        """Create a sample PDB file for testing"""
        pdb_content = """ATOM      1  C1   LIG A   1       0.000   0.000   0.000  1.00  0.00           C
ATOM      2  C2   LIG A   1       1.540   0.000   0.000  1.00  0.00           C
ATOM      3  C3   LIG A   1       2.310   1.331   0.000  1.00  0.00           C
ATOM      4  C4   LIG A   1       3.080   0.665   1.331  1.00  0.00           C
ATOM      5  H1   LIG A   1      -0.540   0.930   0.000  1.00  0.00           H
ATOM      6  H2   LIG A   1      -0.540  -0.930   0.000  1.00  0.00           H
END
"""
        pdb_file = tmp_path / "test.pdb"
        pdb_file.write_text(pdb_content)
        print(f"Sample PDB file created at: {pdb_file}")
        print(f"Content:\n{pdb_content}")
        return str(pdb_file)

    def test_parse_rtf_file(self, sample_rtf_file):
        """Test RTF file parsing"""
        generator = MMFFForceFieldGenerator(ligand_path="test.mol2", output_dir=tempfile.mkdtemp(), overwrite=True)

        rtf_data = generator._parse_rtf_file(sample_rtf_file)

        # Check atoms
        assert "atoms" in rtf_data
        assert len(rtf_data["atoms"]) == 6
        assert "C1" in rtf_data["atoms"]
        assert rtf_data["atoms"]["C1"]["type"] == "CT"
        assert rtf_data["atoms"]["C1"]["charge"] == 0.0

        # Check bonds
        assert "bonds" in rtf_data
        assert len(rtf_data["bonds"]) == 4  # C1-C2, C1-H1, C1-H2, C2-H1

        # Check angles
        assert "angles" in rtf_data
        assert len(rtf_data["angles"]) == 3

        # Check dihedrals
        assert "dihedrals" in rtf_data
        assert len(rtf_data["dihedrals"]) == 2

    def test_parse_rtf_file_ignores_improper_section_when_collecting_bonds(self, tmp_path):
        """IMPR/IMPRO lines must not leak into the active bond section."""
        rtf_file = tmp_path / "improper.rtf"
        rtf_file.write_text(
            """* Test RTF file with impropers
ATOM C1 CT 0.0
ATOM C2 CT 0.0
ATOM C3 CT 0.0
ATOM C4 CT 0.0
ATOM H1 HC 0.0
ATOM H2 HC 0.0

BOND C1 C2
IMPR C1 C2 C3 C4
H1 H2
DIHE C1 C2 C3 C4
"""
        )

        generator = MMFFForceFieldGenerator(ligand_path="test.mol2", output_dir=tempfile.mkdtemp(), overwrite=True)
        rtf_data = generator._parse_rtf_file(str(rtf_file))

        assert rtf_data["bonds"] == [("C1", "C2")]
        assert rtf_data["dihedrals"] == [("C1", "C2", "C3", "C4")]

    def test_parse_pdb_coordinates(self, sample_pdb_file):
        """Test PDB coordinate parsing"""
        output_dir = tempfile.mkdtemp()
        generator = MMFFForceFieldGenerator(ligand_path="test.mol2", output_dir=output_dir, overwrite=True)

        coordinates = generator._parse_pdb_coordinates(sample_pdb_file)

        assert len(coordinates) == 6
        assert "C1" in coordinates
        assert coordinates["C1"] == (0.0, 0.0, 0.0)
        assert coordinates["C2"] == (1.540, 0.0, 0.0)

        shutil.rmtree(output_dir)

    def test_generate_gro_file(self, sample_rtf_file, sample_pdb_file):
        """Test GRO file generation"""
        output_dir = tempfile.mkdtemp()
        generator = MMFFForceFieldGenerator(ligand_path="test.mol2", output_dir=output_dir, overwrite=True)

        rtf_data = generator._parse_rtf_file(sample_rtf_file)
        coordinates = generator._parse_pdb_coordinates(sample_pdb_file)

        generator._generate_gro_file(coordinates, rtf_data)

        # File is in LIG.mmff2gmx subdirectory
        gro_file = os.path.join(output_dir, "LIG.mmff2gmx", "LIG.gro")
        assert os.path.exists(gro_file)

        # Read and verify GRO file content
        with open(gro_file, "r") as f:
            lines = f.readlines()

        assert len(lines) >= 4  # Header, atom count, atoms, box
        assert "Generated by SwissParamForceFieldGenerator" in lines[0]
        assert "6" in lines[1]  # 6 atoms

        shutil.rmtree(output_dir)

    def test_generate_itp_file(self, sample_rtf_file):
        """Test ITP file generation"""
        output_dir = tempfile.mkdtemp()
        generator = MMFFForceFieldGenerator(ligand_path="test.mol2", output_dir=output_dir, overwrite=True)

        rtf_data = generator._parse_rtf_file(sample_rtf_file)
        generator._generate_itp_file(rtf_data)

        # File is in LIG.mmff2gmx subdirectory
        itp_file = os.path.join(output_dir, "LIG.mmff2gmx", "LIG.itp")
        assert os.path.exists(itp_file)

        # Verify ITP file content
        with open(itp_file, "r") as f:
            content = f.read()

        assert "[ moleculetype ]" in content
        assert "[ atoms ]" in content
        assert "[ bonds ]" in content
        assert "[ angles ]" in content
        assert "[ dihedrals ]" in content
        assert "LIG    3" in content  # 3 exclusions

        shutil.rmtree(output_dir)

    def test_generate_atomtypes_file(self, sample_rtf_file):
        """Test atomtypes file generation"""
        output_dir = tempfile.mkdtemp()
        generator = MMFFForceFieldGenerator(ligand_path="test.mol2", output_dir=output_dir, overwrite=True)

        rtf_data = generator._parse_rtf_file(sample_rtf_file)
        generator._generate_atomtypes_file(rtf_data)

        # File is in LIG.mmff2gmx subdirectory
        atomtypes_file = os.path.join(output_dir, "LIG.mmff2gmx", "atomtypes_LIG.itp")
        assert os.path.exists(atomtypes_file)

        with open(atomtypes_file, "r") as f:
            content = f.read()

        assert "[ atomtypes ]" in content
        assert "CT" in content  # Carbon type
        assert "HC" in content  # Hydrogen type

        shutil.rmtree(output_dir)

    def test_generate_posre_file(self, sample_rtf_file):
        """Test position restraints file generation"""
        output_dir = tempfile.mkdtemp()
        generator = MMFFForceFieldGenerator(ligand_path="test.mol2", output_dir=output_dir, overwrite=True)

        rtf_data = generator._parse_rtf_file(sample_rtf_file)
        generator._generate_posre_file(rtf_data)

        # File is in LIG.mmff2gmx subdirectory
        posre_file = os.path.join(output_dir, "LIG.mmff2gmx", "posre_LIG.itp")
        assert os.path.exists(posre_file)

        with open(posre_file, "r") as f:
            content = f.read()

        assert "[ position_restraints ]" in content
        # Should have 6 atoms
        assert content.count("1000") == 18  # 3 force constants * 6 atoms

        shutil.rmtree(output_dir)

    def test_generate_top_file(self):
        """Test topology file generation"""
        output_dir = tempfile.mkdtemp()
        generator = MMFFForceFieldGenerator(ligand_path="test.mol2", output_dir=output_dir, overwrite=True)

        generator._generate_top_file()

        # File is in LIG.mmff2gmx subdirectory
        top_file = os.path.join(output_dir, "LIG.mmff2gmx", "LIG.top")
        assert os.path.exists(top_file)

        with open(top_file, "r") as f:
            content = f.read()

        assert '#include "atomtypes_LIG.itp"' in content
        assert '#include "LIG.itp"' in content
        assert "[ system ]" in content
        assert "LIG" in content
        assert "[ molecules ]" in content

        shutil.rmtree(output_dir)


class TestSwissParamWorkflow:
    """Test full workflow integration"""

    @pytest.fixture
    def mock_tarball_data(self):
        """Create mock tarball data"""
        import tarfile
        import io

        # Create in-memory tarball
        tar_buffer = io.BytesIO()

        with tarfile.open(fileobj=tar_buffer, mode="w:gz") as tar:
            # Add mock RTF file
            rtf_content = b"* Test\nATOM C1 CT 0.0\n"
            rtf_file = io.BytesIO(rtf_content)
            tarinfo = tarfile.TarInfo(name="test.rtf")
            tarinfo.size = len(rtf_content)
            tar.addfile(tarinfo, rtf_file)

            # Add mock PDB file
            pdb_content = b"ATOM      1  C1   LIG A   1       0.000   0.000   0.000  1.00  0.00           C\nEND\n"
            pdb_file = io.BytesIO(pdb_content)
            tarinfo = tarfile.TarInfo(name="test.pdb")
            tarinfo.size = len(pdb_content)
            tar.addfile(tarinfo, pdb_file)

        tar_buffer.seek(0)
        return tar_buffer.read()

    def test_check_required_files_with_prism_files(self):
        """Test check_required_files with complete PRISM files"""
        output_dir = tempfile.mkdtemp()

        # Create all required PRISM files
        required_files = ["LIG.gro", "LIG.itp", "LIG.top", "atomtypes_LIG.itp", "posre_LIG.itp"]
        for filename in required_files:
            Path(output_dir, filename).touch()

        generator = MMFFForceFieldGenerator(ligand_path="test.mol2", output_dir=output_dir, overwrite=False)

        assert generator.check_required_files(output_dir) is True

        shutil.rmtree(output_dir)

    def test_check_required_files_with_rtf_files(self):
        """Test check_required_files with RTF files that can be converted"""
        output_dir = tempfile.mkdtemp()

        # Create RTF and PDB files
        Path(output_dir, "test.rtf").touch()
        Path(output_dir, "test.pdb").touch()

        generator = MMFFForceFieldGenerator(ligand_path="test.mol2", output_dir=output_dir, overwrite=False)

        assert generator.check_required_files(output_dir) is True

        shutil.rmtree(output_dir)

    def test_check_required_files_missing_all(self):
        """Test check_required_files with missing files"""
        output_dir = tempfile.mkdtemp()

        generator = MMFFForceFieldGenerator(ligand_path="test.mol2", output_dir=output_dir, overwrite=False)

        assert generator.check_required_files(output_dir) is False

        shutil.rmtree(output_dir)

    @patch("prism.forcefield.swissparam.subprocess.run")
    def test_api_submission_error_handling(self, mock_run):
        """Test error handling during API submission"""
        # Mock curl failure
        mock_run.return_value = Mock(returncode=1, stderr=b"curl: Connection failed")

        output_dir = tempfile.mkdtemp()

        # Create a dummy ligand file
        ligand_file = Path(output_dir, "test.mol2")
        ligand_file.write_text("dummy")

        generator = MMFFForceFieldGenerator(ligand_path=str(ligand_file), output_dir=output_dir, overwrite=True)

        with pytest.raises(RuntimeError, match="curl failed"):
            generator._submit_to_swissparam_api()

        shutil.rmtree(output_dir)

    @patch("prism.forcefield.swissparam.subprocess.run")
    def test_api_submission_accepts_small_gzip_tarball(self, mock_run):
        """Small gzip tarballs from SwissParam should not be rejected as incomplete."""
        import io
        import tarfile

        tar_buffer = io.BytesIO()
        with tarfile.open(fileobj=tar_buffer, mode="w:gz") as tar:
            content = b"ok\n"
            tarinfo = tarfile.TarInfo(name="tiny.txt")
            tarinfo.size = len(content)
            tar.addfile(tarinfo, io.BytesIO(content))
        tar_data = tar_buffer.getvalue()
        assert len(tar_data) < 1000

        mock_run.return_value = Mock(returncode=0, stdout=tar_data, stderr=b"")

        output_dir = tempfile.mkdtemp()
        ligand_file = Path(output_dir, "test.mol2")
        ligand_file.write_text("dummy")
        generator = MMFFForceFieldGenerator(ligand_path=str(ligand_file), output_dir=output_dir, overwrite=True)

        result = generator._submit_to_swissparam_api()

        assert result == tar_data

        shutil.rmtree(output_dir)

    @patch("prism.forcefield.swissparam.subprocess.run")
    def test_api_submission_session_polling(self, mock_run):
        """Queued SwissParam sessions should be polled and retrieved."""
        import io
        import tarfile

        tar_buffer = io.BytesIO()
        with tarfile.open(fileobj=tar_buffer, mode="w:gz") as tar:
            content = b"ok\n"
            tarinfo = tarfile.TarInfo(name="tiny.txt")
            tarinfo.size = len(content)
            tar.addfile(tarinfo, io.BytesIO(content))
        tar_data = tar_buffer.getvalue()
        assert len(tar_data) < 1000

        mock_run.side_effect = [
            Mock(returncode=0, stdout=b"Session number: 12345", stderr=b""),
            Mock(returncode=0, stdout=b"Calculation is finished", stderr=b""),
            Mock(returncode=0, stdout=tar_data, stderr=b""),
        ]

        output_dir = tempfile.mkdtemp()
        ligand_file = Path(output_dir, "test.mol2")
        ligand_file.write_text("dummy")
        generator = MMFFForceFieldGenerator(ligand_path=str(ligand_file), output_dir=output_dir, overwrite=True)

        result = generator._submit_to_swissparam_api()

        assert result == tar_data
        assert mock_run.call_count == 3

        shutil.rmtree(output_dir)


class TestSwissParamApproaches:
    """Test different SwissParam approaches"""

    def test_mmff_approach(self):
        """Test MMFF-based approach"""
        output_dir = tempfile.mkdtemp()
        generator = MMFFForceFieldGenerator(ligand_path="test.mol2", output_dir=output_dir, overwrite=True)

        assert generator.approach == "mmff-based"
        assert "mmff2gmx" in generator.get_output_dir_name()

        shutil.rmtree(output_dir)

    def test_match_approach(self):
        """Test MATCH approach"""
        output_dir = tempfile.mkdtemp()
        generator = MATCHForceFieldGenerator(ligand_path="test.mol2", output_dir=output_dir, overwrite=True)

        assert generator.approach == "match"
        assert "match2gmx" in generator.get_output_dir_name()

        shutil.rmtree(output_dir)

    def test_invalid_approach(self):
        """Test invalid approach raises error"""
        output_dir = tempfile.mkdtemp()

        with pytest.raises(ValueError, match="Invalid approach"):
            SwissParamForceFieldGenerator(
                ligand_path="test.mol2", output_dir=output_dir, approach="invalid", overwrite=True
            )

        shutil.rmtree(output_dir)


class TestErrorHandling:
    """Test error handling and edge cases"""

    def test_parse_empty_rtf(self, tmp_path):
        """Test parsing empty RTF file"""
        empty_rtf = tmp_path / "empty.rtf"
        empty_rtf.write_text("")

        output_dir = tempfile.mkdtemp()
        generator = MMFFForceFieldGenerator(ligand_path="test.mol2", output_dir=output_dir, overwrite=True)

        rtf_data = generator._parse_rtf_file(str(empty_rtf))
        assert len(rtf_data["atoms"]) == 0
        assert len(rtf_data["bonds"]) == 0

        shutil.rmtree(output_dir)

    def test_parse_malformed_rtf(self, tmp_path):
        """Test parsing malformed RTF file doesn't crash"""
        malformed_rtf = tmp_path / "malformed.rtf"
        malformed_rtf.write_text("INVALID DATA HERE\nATOM C1\n")

        output_dir = tempfile.mkdtemp()
        generator = MMFFForceFieldGenerator(ligand_path="test.mol2", output_dir=output_dir, overwrite=True)

        # Should not crash, just return empty or partial data
        rtf_data = generator._parse_rtf_file(str(malformed_rtf))
        assert "atoms" in rtf_data

        shutil.rmtree(output_dir)

    def test_missing_pdb_coordinates(self, tmp_path):
        """Test handling of missing PDB coordinates"""
        empty_pdb = tmp_path / "empty.pdb"
        empty_pdb.write_text("END\n")

        output_dir = tempfile.mkdtemp()
        generator = MMFFForceFieldGenerator(ligand_path="test.mol2", output_dir=output_dir, overwrite=True)

        coordinates = generator._parse_pdb_coordinates(str(empty_pdb))
        assert len(coordinates) == 0

        shutil.rmtree(output_dir)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
