#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Integration test for SwissParam RTF parsing with real-world files
Tests the complete workflow from RTF/PDB files to PRISM format generation
"""

import pytest
import os
import sys
import tempfile
import shutil
from pathlib import Path

# Add PRISM to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from prism.forcefield.swissparam import MMFFForceFieldGenerator


class TestSwissParamRealWorld:
    """Integration tests with real-world files"""

    def test_ethanol_rtf_workflow(self):
        """
        Test complete RTF → PRISM workflow using a simple ethanol-like molecule
        This simulates what would happen with actual SwissParam output files
        """
        # Create realistic RTF file for ethanol
        rtf_content = """* Ethanol RTF file (simplified)
MASS

BOND C1 C2 C2 O1
ANGLE C1 C2 O1 H1 C2 H2
DIHEDRAL C1 C2 O1 H3

ATOM C1 CT 0.0
ATOM C2 CT 0.0
ATOM O1 OT 0.0
ATOM H1 HC 0.0
ATOM H2 HC 0.0
ATOM H3 HO 0.0
ATOM H4 HC 0.0
ATOM H5 HC 0.0
ATOM H6 HC 0.0

BOND C1 H4 C1 H5 C1 H6 C2 H1 C2 H2 O1 H3

ANGLE H4 C1 H5 H4 C1 H5 H1 C2 H2 H1 C2 O1

END
"""

        # Create realistic PDB file
        pdb_content = """ATOM      1  C1   ETH A   1       0.000   0.000   0.000  1.00  0.00           C
ATOM      2  C2   ETH A   1       1.540   0.000   0.000  1.00  0.00           C
ATOM      3  O1   ETH A   1       2.200   1.200   0.000  1.00  0.00           O
ATOM      4  H1   ETH A   1       1.900  -0.500  -0.900  1.00  0.00           H
ATOM      5  H2   ETH A   1       1.900  -0.500   0.900  1.00  0.00           H
ATOM      6  H3   ETH A   1       3.200   1.200   0.000  1.00  0.00           H
ATOM      7  H4   ETH A   1      -0.540   0.000  -0.930  1.00  0.00           H
ATOM      8  H5   ETH A   1      -0.540   0.890   0.270  1.00  0.00           H
ATOM      9  H6   ETH A   1      -0.540  -0.890   0.270  1.00  0.00           H
END
"""

        output_dir = tempfile.mkdtemp()

        try:
            # Create test files
            rtf_file = Path(output_dir) / "ethanol.rtf"
            pdb_file = Path(output_dir) / "ethanol.pdb"
            ligand_file = Path(output_dir) / "ethanol.mol2"

            rtf_file.write_text(rtf_content)
            pdb_file.write_text(pdb_content)
            ligand_file.write_text("dummy mol2")

            # Create generator
            generator = MMFFForceFieldGenerator(ligand_path=str(ligand_file), output_dir=output_dir, overwrite=True)

            # Parse RTF and PDB
            rtf_data = generator._parse_rtf_file(str(rtf_file))
            coordinates = generator._parse_pdb_coordinates(str(pdb_file))

            # Verify parsing results
            assert len(rtf_data["atoms"]) == 9, "Should have 9 atoms"
            assert len(rtf_data["bonds"]) == 8, "Should have 8 bonds"
            assert len(coordinates) == 9, "Should have coordinates for 9 atoms"

            # Generate all PRISM format files
            generator._generate_gro_file(coordinates, rtf_data)
            generator._generate_itp_file(rtf_data)
            generator._generate_atomtypes_file(rtf_data)
            generator._generate_posre_file(rtf_data)
            generator._generate_top_file()

            # Verify all output files exist
            output_subdir = os.path.join(output_dir, "LIG.mmff2gmx")
            required_files = ["LIG.gro", "LIG.itp", "LIG.top", "atomtypes_LIG.itp", "posre_LIG.itp"]

            for filename in required_files:
                filepath = os.path.join(output_subdir, filename)
                assert os.path.exists(filepath), f"Missing required file: {filename}"

            # Verify GRO file content
            gro_file = os.path.join(output_subdir, "LIG.gro")
            with open(gro_file, "r") as f:
                gro_content = f.read()

            assert "9" in gro_content.split("\n")[1], "Should have 9 atoms in GRO file"
            assert "Generated by SwissParamForceFieldGenerator" in gro_content

            # Verify ITP file structure
            itp_file = os.path.join(output_subdir, "LIG.itp")
            with open(itp_file, "r") as f:
                itp_content = f.read()

            assert "[ moleculetype ]" in itp_content
            assert "[ atoms ]" in itp_content
            assert "[ bonds ]" in itp_content
            assert itp_content.count("CT") > 0, "Should have carbon atom types"
            assert itp_content.count("OT") > 0, "Should have oxygen atom types"

            # Verify topology file
            top_file = os.path.join(output_subdir, "LIG.top")
            with open(top_file, "r") as f:
                top_content = f.read()

            assert '#include "atomtypes_LIG.itp"' in top_content
            assert '#include "LIG.itp"' in top_content
            assert "[ system ]" in top_content
            assert "LIG" in top_content

            print("✓ Ethanol RTF workflow test passed successfully")

        finally:
            shutil.rmtree(output_dir)

    def test_prism_format_compatibility(self):
        """
        Test that generated PRISM files are compatible with PRISM base class expectations
        """
        # Create minimal test files
        rtf_content = """* Minimal RTF
ATOM C1 CT 0.0
ATOM H1 HC 0.0

BOND C1 H1
END
"""

        pdb_content = """ATOM      1  C1   LIG A   1       0.000   0.000   0.000  1.00  0.00           C
ATOM      2  H1   LIG A   1       1.090   0.000   0.000  1.00  0.00           H
END
"""

        output_dir = tempfile.mkdtemp()

        try:
            # Create test files
            rtf_file = Path(output_dir) / "test.rtf"
            pdb_file = Path(output_dir) / "test.pdb"
            ligand_file = Path(output_dir) / "test.mol2"

            rtf_file.write_text(rtf_content)
            pdb_file.write_text(pdb_content)
            ligand_file.write_text("dummy")

            # Generate PRISM files
            generator = MMFFForceFieldGenerator(ligand_path=str(ligand_file), output_dir=output_dir, overwrite=True)

            rtf_data = generator._parse_rtf_file(str(rtf_file))
            coordinates = generator._parse_pdb_coordinates(str(pdb_file))

            generator._generate_gro_file(coordinates, rtf_data)
            generator._generate_itp_file(rtf_data)
            generator._generate_atomtypes_file(rtf_data)
            generator._generate_posre_file(rtf_data)
            generator._generate_top_file()

            # Check that files match ForceFieldGeneratorBase expectations
            output_subdir = os.path.join(output_dir, "LIG.mmff2gmx")

            # Test check_required_files
            assert generator.check_required_files(
                output_subdir
            ), "Generated files should pass ForceFieldGeneratorBase validation"

            print("✓ PRISM format compatibility test passed")

        finally:
            shutil.rmtree(output_dir)

    def test_coordinate_conversion_accuracy(self):
        """
        Test that PDB to GRO coordinate conversion is accurate
        """
        # Test coordinate conversion: Å → nm (divide by 10)
        pdb_content = """ATOM      1  C1   LIG A   1      10.000  20.000  30.000  1.00  0.00           C
END
"""

        output_dir = tempfile.mkdtemp()

        try:
            pdb_file = Path(output_dir) / "test.pdb"
            ligand_file = Path(output_dir) / "test.mol2"

            pdb_file.write_text(pdb_content)
            ligand_file.write_text("dummy")

            generator = MMFFForceFieldGenerator(ligand_path=str(ligand_file), output_dir=output_dir, overwrite=True)

            coordinates = generator._parse_pdb_coordinates(str(pdb_file))

            # Check PDB parsing (in Å)
            assert "C1" in coordinates
            x_angstrom, y_angstrom, z_angstrom = coordinates["C1"]
            assert abs(x_angstrom - 10.0) < 0.01, "X coordinate should be 10.0 Å"
            assert abs(y_angstrom - 20.0) < 0.01, "Y coordinate should be 20.0 Å"
            assert abs(z_angstrom - 30.0) < 0.01, "Z coordinate should be 30.0 Å"

            # Create RTF data for GRO generation
            rtf_data = {"atoms": {"C1": {"type": "CT", "charge": 0.0}}}
            generator._generate_gro_file(coordinates, rtf_data)

            # Check GRO file (should be in nm)
            gro_file = os.path.join(output_dir, "LIG.mmff2gmx", "LIG.gro")
            with open(gro_file, "r") as f:
                gro_lines = f.readlines()

            # Find the atom line
            atom_line = None
            for line in gro_lines:
                if "C1" in line and not line.strip().startswith(";"):
                    atom_line = line
                    break

            assert atom_line is not None, "Should find C1 atom line in GRO file"

            # Extract coordinates from GRO line (format: ... x y z)
            parts = atom_line.split()
            x_nm = float(parts[-3])
            y_nm = float(parts[-2])
            z_nm = float(parts[-1])

            # Check conversion: 10 Å = 1.0 nm, 20 Å = 2.0 nm, 30 Å = 3.0 nm
            assert abs(x_nm - 1.0) < 0.01, f"X coordinate should be 1.0 nm, got {x_nm}"
            assert abs(y_nm - 2.0) < 0.01, f"Y coordinate should be 2.0 nm, got {y_nm}"
            assert abs(z_nm - 3.0) < 0.01, f"Z coordinate should be 3.0 nm, got {z_nm}"

            print("✓ Coordinate conversion accuracy test passed")

        finally:
            shutil.rmtree(output_dir)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
